README.md

To help users copy and paste the command with the right indentation for the yaml file

Fix  helm command indentation

---

bin/run-smoke-tests.sh
tests/smoke/smoke_test.go

Adds a script to run the smoke tests. 
> _Include any links to other PRs, stories, slack discussions, etc... that will help establish context._
1. Set appropriate environment variables 
1. Run `./bin/run-smoke-tests.sh`
> _Please specify either kubectl or cf cli commands for our team (and cf operators) to verify the changes._
@cwlbraa 

Add script for running smoke tests (& improve feedback on running the smoke tests)

---

docs/deploy.md

1. Adds cluster requirements
2. Update deploy docs to add clarity
> _Include any links to other PRs, stories, slack discussions, etc... that will help establish context._
> _Please specify either kubectl or cf cli commands for our team (and cf operators) to verify the changes._
> _Few examples_
> 1. For a PR with a new ytt library that contains a Deployment resource definition, `kubectl get deployment <NAME_OF_DEPLOYMENT_RESOURCE>` can verify the new deployment is created. You can provide additional commands to verify the new resources are created/functional
- Given that I follow the instructions in deploy.md, I should be able to install and validate CF4K8s without any assistance
> _It's helpful to tag …

Add cluster requirements, add additional insructions to deploy docs

---

docs/deploy.md

Update the deploy doc to include details about the domains that self-generated certificates need to be valid for.
https://pivotal.slack.com/archives/CPPEXT81M/p1581544584336500

docs: Add certificate SAN requirements

---

docs/deploy.md

> _Please describe the change._
> _Include any links to other PRs, stories, slack discussions, etc... that will help establish context._
> _Please specify either kubectl or cf cli commands for our team (and cf operators) to verify the changes._
> _Few examples_
> 1. For a PR with a new ytt library that contains a Deployment resource definition, `kubectl get deployment <NAME_OF_DEPLOYMENT_RESOURCE>` can verify the new deployment is created. You can provide additional commands to verify the new resources are created/functional

Fix typo in instructions

---

README.md

Add a link to the main readme to the contributor flow

Add contributors link to main readme

---

docs/deploy.md

🚫 We only accept PRs to `develop` branch. If this is an exception, please specify why 🚫
Add delete instruction to the docs. I noticed folks don't know how to delete CF4K8s bcoz the script hides `kapp install -a  cf`

Adding delete app instruction

---

docs/deploy.md

> _Please describe the change._ 
We noticed this change to generate values!
**Acceptance Criteria**
Observe the docs!
_Resources_
https://github.com/cloudfoundry/cf-for-k8s/blob/master/hack/generate-values.sh#L12-L18
@tcdowney @Syerram

Update docs for the new generate-values.sh signature

---

config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/values.yml
vendir.lock.yml
vendir.yml

[#172086817](https://www.pivotaltracker.com/story/show/172086817)
Co-authored-by: Seth Boyles <sboyles@pivotal.io>
Co-authored-by: Renee Chu <rchu@pivotal.io>
>
---
_please provide a series of instructions (eg kubectl or cf cli …

Update capi-k8s-release version for pinning capi images

---

config/_ytt_lib/github.com/pivotal/kpack/release-0.0.8.yaml
vendir.lock.yml
vendir.yml

>
This change updates kpack to 0.0.8
---
_please provide a series of instructions (eg kubectl or cf cli commands) for how our Product Manager can verify that your changes were properly integrated_
> _It's helpful to tag a few other …

Bump kpack to 0.0.8

---

docs/debugging.md

- Add formatting
- Add how-to-fix it with examples.
---

Format + add how-to fix

---

docs/deploy.md

This simply cleans up some markdown formatting for our deploy.md doc
---
My first attempt at this messed up the intended numbering of numbered lists and sub-lists. Now, the only intended changes are:
1. remove `$` command prompt from code snippets to make copy-and-paste-ing easier
1. minor correction/addition at the end of the doc

STY: lint deploy.md

---

docs/deploy.md

- Add cf-cli version requirements
- Add kapp version requirements
- Add known issues
- Remove docker image instructions
cf push works

Add cf-cli version requirements and simplify deploy documentation

---

config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/300-fluentd-config.yaml
config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/400-fluent-ingress-service.yaml
config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/500-fluentd-daemonset.yaml
config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/500-log-cache-deployment.yaml
config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/values.yml
config/logging.yml
config/values.yml
hack/generate-values.sh
vendir.lock.yml
vendir.yml

- Build logs now included in cf-push
- remove uaa client from log-cache
- add forwarder api to fluentd
- When cf-pushing an app with build logs they should appear while pushing
@pianohacker @MasslessParticle @JSchuenke

update logging to 0.2.0

---

bin/install-cf.sh
build/eirini/build.sh
build/minio/build.sh
build/postgres/build.sh
config/values.yml
hack/confirm-network-policy.sh
hack/generate-values.sh
hack/run-smoke-tests.sh

>
This makes shellcheck happy most places in our current bash files.
---
This shouldn't cause any functional changes.

STY: improve formatting of bash scripts

---

docs/deploy.md

Now that we are not using install script, adding more clarity on the raw commands.

Update deploy instructions

---

config/uaa.yml

Creating a PR to test some pipeline changes. This also completes [#172539075](https://www.pivotaltracker.com/story/show/172539075)
Co-authored-by: Dave Walter <dwalter@pivotal.io>
>
---
When you deploy with this branch, you should …

MAINT: remove UAA namespace overlay

---

config/_ytt_lib/github.com/cloudfoundry/metric-proxy/config/values.yml
vendir.lock.yml
vendir.yml

[#172921741]
Signed-off-by: Louie Brann <lbrann@pivotal.io>
@louis-brann @hev

Annotate metric-proxy image

---

docs/configuration/external-databases.md
docs/deploy.md

I think it might be helpful to add some documentation to configure the installed cloud foundry in a certain way. At some point, there will probably be a more general approach to document stuff like this, but in the meantime this would have helped us to apply the wanted configuration.
Please have a look if you see this as beneficial as well.

Add documentation how to enable external ccdb und uaadb

---

config/uaa.yml
hack/generate-values.sh
sample-cf-install-values.yml

[#173674556](https://www.pivotaltracker.com/story/show/173674556)
Co-authored-by: Lisa Burns <lcho@pivotal.io>
Co-authored-by: Julian Hjortshoj <hjortshojj@vmware.com>

Conditionally override UAA SAML config

---

config/capi.yml
config/uaa.yml
config/values.yml

https://www.pivotaltracker.com/story/show/173753231

Add new secrets

---

config/eirini/eirini.yml

Better pattern for applying overlays to encoded yaml
Private slack convo: https://vmware.slack.com/archives/CUK1X0Z8Q/p1595441763103900

Move to better ytt pattern for encoded overlays

---

config/kpack/_ytt_lib/kpack/kpack-rendered.yml

Use specific kpack image references to unblock capi in preparation of integrating breaking changes coming in from both components.
Standard deployment process and smoke tests continue to work.
cc @ericpromislow

Update kpack images

---

docs/platform_operators/external-databases.md

>
Fix typo in supplied example
---
- Is …

Correct missing # sign in aws rds example db-values.yml

---

ci/pipelines/cf-for-k8s.yml
ci/tasks/install-cf-on-gke/task.sh
ci/tasks/install-cf-on-gke/task.yml
ci/tasks/install-postgres/task.sh
ci/tasks/install-postgres/task.yml

Add a check for external DB functionality to pull request checks in the concourse pipeline (#168)
We could not test this on our concourse. Integrations and configurations for GCP are missing.
*Acceptance Steps**
Update Concourse Pipeline and see if new pull request steps are working
@kramerul

Add external db check on pr to ci pipeline

---

build/eirini/osl-compliant-image-override.yml
config/eirini/_ytt_lib/eirini/rendered.yml

MAINT: Annotate eirini images
[#174240799](https://www.pivotaltracker.com/story/show/174240799)
Co-Authored-by: Paul Warren <pwarren@pivotal.io>
Co-Authored-by: Carlos Iriarte <ciriarte@pivotal.io>
>
---
- Checkout the [contributing …

MAINT: Add eirini image annotation

---

.github/PULL_REQUEST_TEMPLATE.md

- Rearrange the PR questions, so it is more readable
- Add a new question "Does this PR introduce a change to `config/values.yml`
>
---
- Include any …

Update Pull request

---

docs/platform_operators/ingress-routing-topology.md

Removed from cf-k8s-networking
[#174224247](https://www.pivotaltracker.com/story/show/174224247)
@mike1808

Routing Topology docs

---

docs/platform_operators/deploy-parameters.md

[#174157113](https://www.pivotaltracker.com/story/show/174157113)
Signed-off-by: Andrew Costa <acosta@pivotal.io>
This adds docs per [Tracker #174157113
](https://www.pivotaltracker.com/story/show/174157113)
No functional changes.
[Tracker #174157113
](https://www.pivotaltracker.com/story/show/174157113)

Add documentation for configurable properties

---

docs/platform_operators/router-access-logs.md

Updated the description of the log fields emitted by the ingress gateway

---

docs/platform_operators/router-access-logs.md

added reference to envoy docs for `response_flag`

---

docs/platform_operators/router-access-logs.md

updated description for `upstream_transport_failure_reason`

---

docs/platform_operators/router-access-logs.md

updated `start_time` description

---

config/values/20-secrets-config-values.yml

>
Yes, it removes an unused value from `values/20-secrets-config-values.yml`
Smoketests/PR tests pass

MAINT: remove metric_proxy cert from values/20-secrets-config-values.yml

---

docs/deploy.md
docs/platform_operators/external-blobstore.md

Add documentation on how to use external blobstores.
No
Try it out.
@phil9909 
@loewenstein

Add documentation on how to use external blobstores

---

ci/pipelines/cf-for-k8s-contributions.yml
ci/pipelines/cf-for-k8s-main.yml
ci/tasks/install-cf-on-gke/task.sh
ci/tasks/install-cf-on-gke/task.yml
ci/tasks/install-minio/task.sh
ci/tasks/install-minio/task.yml
ci/tasks/run-external-blobstore-validation-test/task.sh
ci/tasks/run-external-blobstore-validation-test/task.yml
ci/templates/cf-for-k8s-contributions.yml

With this chance we ensure that CF can be installed and used with an external in-cluster blobstore. This behaviour is verified for the develop branch and all PRs. See #344 for details.
No
Set the pipelines and try it out.
@phil9909 
@loewenstein

Validate external blobstore

---

config/kpack/default-buildpacks.yml

New order of buildpacks based on advice from the buildpack team in
https://github.com/paketo-buildpacks/builder/blob/main/rfcs/0001-buildpack-order.md
>
https://www.pivotaltracker.com/story/show/174578126
No
See https://www.pivotaltracker.com/story/show/174578126
@davewalter 
[x] - Make sure this PR is based off the `develop` branch
[x] - Include any links to related PRs, issues, stories, slack discussions, etc... that will help establish context.
[x] No - Is there anything else of note that the reviewers should know about this change?
[x] N/A - Our CI uses concourse task files from HEAD of the `develop` branch. If your PR includes/requires CI changes, …

Reorder buildpacks

---

docs/platform_operators/sidecar-access-logs.md

updated `duration` field description

---

vendir.lock.yml
vendir.yml

We are updating cf-for-k8s to use the latest changes of cf-k8s-networking
No
Deploy cf-for-k8s and ensure the smoke tests pass.
@ndhanushkodi

cf-for-k8s now uses the latest networking changes

---

build/istio/values.yaml
config/istio/istio-generated/xxx-generated-istio.yaml

Update Istio sidecar's fluent-bit image digest
No
Deploy succeeds and you can view access logs for the apps

Update Istio sidecar fluent-bit image

---

config/capi/capi.yml
config/eirini/eirini.yml
config/istio/app-sidecar.yaml
config/istio/external-routing.yml
config/istio/fluent-bit-ingressgateway-config-map.yaml
config/istio/gateway.lib.yml
config/istio/peer-auth-fluentd.yaml
config/istio/upgrade-istio-sidecars-job.yml
config/kpack/default-buildpacks.yml
config/logging/logging.yml
config/metrics/metrics.yml
config/namespaces.star
config/networking/istio-authorization-policies.yml
config/networking/network-policies.yaml
config/networking/networking.yml
config/system-namespace.yml
config/uaa/uaa.yml
config/values/10-system-values.yml
config/workloads-namespace.yml
tests/ytt/uaa_test.go

Replace namespace data values with internal functions
See #431
Yes
Deploy cf-for-k8s and run smoke-tests

Replace namespace data values with internal functions

---

ci/pipelines/cf-for-k8s-iaas-tests.yml
ci/pipelines/cf-for-k8s-stability-tests.yml
ci/tasks/install-cf-on-gke/task.sh
ci/tasks/install-cf-on-kind/task.sh
config/istio/external-routing.yml
config/istio/ingressgateway-service-nodeport.yml
config/values/00-values.yml
docs/deploy-local.md
docs/platform_operators/deploy-parameters.md
docs/platform_operators/setup-static-loadbalancer-ip.md
hack/generate-values.sh
sample-cf-install-values.yml

[#174852214](https://www.pivotaltracker.com/story/show/174852214)
Co-authored-by: James Pollard <pollardja@vmware.com>
Make the property more general. It specifies the IP where the load balancer lives, but doesn't need to say which kind of load balancer is in use.
Yes it does
PR tests should be sufficient
@jamespollard8 
[x] - Make sure this PR is based off the `develop` branch
- Everything else is N/A

rename `istio_static_ip` field name to `load_balancer.static_ip`

---

docs/platform_operators/rotating-ingress-certs.md
docs/platform_operators/rotating-secrets-and-certs.md

Documenting ingress certificate rotation
No
When I navigate to `cf-for-k8s/docs/platform_operators/rotating-ingress-certs.md`
I can understand how to rotate my ingress certs
@astrieanna @keshav-pivotal @shalako 
https://www.pivotaltracker.com/story/show/174833269

Document ingress certificate rotation

---

config/logging/logging.yml
config/networking/network-policies.yaml
config/values/00-values.yml
docs/deploy.md

- add aggregate drains/app_log_destinations
- improve fluent performance
- add promtheus metrics
- move some network policy into the logging project
Yes, it adds a optional app_log_destinations value. Should be defaulted to empty
@pianohacker

update logging to 0.4.0

---

ci/tasks/bump-stack/task.sh
config/kpack/default-buildpacks.yml

[#175053873](https://www.pivotaltracker.com/story/show/175053873)

Use full paketo build and run bionic stack images

---

ci/pipelines/cf-for-k8s-iaas-tests.yml
ci/tasks/create-minikube-cluster/task.sh
ci/tasks/create-minikube-cluster/task.yml
config/capi/capi.yml
docs/deploy-local.md

This set of changes implements a concourse job to test a facsimile of a dev environment. Additionally, the `cf-api-server` is scaled down to 1 replica.
This corresponds to this work item: [#171502800](https://www.pivotaltracker.com/story/show/171502800)

171502800 minikube 6cpu 6gbmem

---

docs/maintaining/long-running-environment.md
docs/platform-availability.md

This is just a docs change - and I'm hoping to get feedback on it from a couple of teammates.

DOC: add playbook and info for maintaining the long-running environment

---

config/kpack/_ytt_lib/kpack/release-0.2.0.yaml
config/z-kapp-versioned-creds.yml
vendir.lock.yml
vendir.yml

This happened once through CI but then caused several of our tests to fail. I've opened this PR to test against our full suite of PR tests.

Bump kpack to v0.2.0

---

docs/deploy.md
docs/platform-availability.md
docs/platform_operators/README.md
docs/platform_operators/upgrades.md

Tracker Story: [#175088256](https://www.pivotaltracker.com/story/show/175088256)
We took a stab at adding some docs to help a platform operator understand how to upgrade cf-for-k8s and some things to consider. Submitting it as a PR to get feedback from others (feel free to add suggestions via the code review tool!)
No 🙅 
@jspawar

DOC: Add guidance around cf-for-k8s upgrades

---

build/istio/values.yaml
ci/tasks/generate-release-notes/task.sh
config/istio/istio-generated/xxx-generated-istio.yaml
config/istio/upgrade-istio-sidecars-job.yml

Upgrade Istio to 1.9.4
No.
Deploy as normal.
@davewalter

Upgrade Istio to 1.9.4

---

build/istio/values.yaml
config/istio/istio-generated/xxx-generated-istio.yaml
config/istio/istio-version.star

Bump Istio to latest 1.11.x patch.
No.
@davewalter

Bump Istio to 1.11.8

---

build/istio/istioctl-values.yaml
build/istio/values.yaml
config/istio/istio-generated/xxx-generated-istio.yaml
config/istio/istio-version.star

Bump Istio to 1.12.6
No.
@davewalter

Bump Istio to 1.12.6

---

build/istio/values.yaml
config/istio/istio-generated/xxx-generated-istio.yaml
config/istio/istio-version.star

Bump to Istio 1.13.2
No.
@davewalter

Bump to Istio 1.13.2

---

build/istio/values.yaml
config/istio/istio-generated/xxx-generated-istio.yaml
config/istio/istio-version.star

Patch bump for Istio
No.
Test as normal.

Bump Istio to 1.13.3

---

build/istio/overlays/kapp-compatible.yaml
build/istio/values.yaml
config/istio/istio-generated/xxx-generated-istio.yaml
config/istio/istio-version.star

Bump to Istio 1.14.0
No.
@PureMunky

Upgrade Istio to 1.14.0

---

ci/pipelines/cf-for-k8s-contributions.yml
ci/tasks/run-cats/task.yml
config/kpack/default-buildpacks.yml

Manually bump buildpacks to latest

---

build/istio/values.yaml
config/istio/istio-generated/xxx-generated-istio.yaml
config/istio/istio-version.star

Bump Istio to latest patch release.
No.
@PureMunky

Bump Istio to 1.14.2

---

supported_k8s_versions.yml

Increase supported Kubernetes version range.
No.
@PureMunky

Increase supported K8s version range
