cloudfoundry/cf-for-k8s

config/metacontroller-namespace-overlay.yml
config/system-namespace.yml
config/workloads-namespace.yml

We want to enable automatic sidecar injection to have automatic mTLS between cf-for-k8s workloads (both system components and apps). See [our ADR](https://github.com/cloudfoundry/cf-k8s-networking/blob/master/doc/architecture-decisions/0004-strategy-for-securing-network-traffic.md) for a bit more explanation.
As we discussed on Slack, we attempted the `ytt` overlay approach. Happy to pair with y'all on this if you would like it to work differently.
Fixes https://github.com/cloudfoundry/cf-for-k8s/issues/3.
[Story: #170980509](https://www.pivotaltracker.com/story/show/170980509)
Thanks!
@mike1808 && @tcdowney

Enable Istio automatic sidecar injection

---

bin/install-cf.sh

The values file is required. 
There is a comment about improving it, but failing fast would be more visible

Fail on unknown environment variable

---

config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/api_server_deployment.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-config.lib.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-configmap.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/clock_deployment.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/deployment_updater_deployment.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/namespace.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/nginx-configmap.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/opi-secrets.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/service.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/worker_deployment.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/values.yml
vendir.lock.yml
vendir.yml

@tcdowney & friends were having issues with the way capi-k8s-release adds an extra namespace template to the whole cf-for-k8s collection. We removed that template and bumped capi-k8s-release. That brings in a few more changes, like versioned ConfigMaps and templating the namespace in other contexts (service dns names, mostly).
https://github.com/cloudfoundry/cf-for-k8s/pull/12 the PR this should hopefully unblock
1. It still kapp deploys
2. only 1 system namespace appears in the pre-deploy templates
3. capi deployments roll when ConfigMaps change. 
@cwlbraa 

bump capi-k8s-release

---

tests/smoke/smoke_test.go

Delete organisation only if it is created
I used a wrong password and the test was running for a long time.

Delete cf org only if it is created

---

docs/deploy.md

My pair and I were deploying cf-for-k8s this morn and were shocked (🤯) to discover we needed to have the `bosh` (BOSH Outer Shell) CLI  installed for generating values. Can we note this in the requirements? Thanks!
https://github.com/cloudfoundry/cf-for-k8s/blob/73f18c5733b25e291a0a4bd7d4dd4bfeeda43032/hack/generate-values.sh#L66-L70
- [] NO
@ndhanushkodi 
You could also add `ytt interpolate`. 👍

docs: clarify that the BOSH cli is required for generating values

---

hack/generate-values.sh

* `bosh interpolate` reuses vars from varstore file if the file exists
so if you reuse this scipt for a new environment the certificate
generation won't happen and they will contain old domains
Put CF vars to unique temp dir
`bosh interpolate` reuses vars from varstore file if the file exists
so if you reuse this scipt for a new environment the certificate
generation won't happen and they will contain old domains
> _Please specify either kubectl or cf cli commands for our team (and cf operators) to verify the changes._
Redeploy using hack scripts and check that system components can communicate with UAA. Or check the certificates that SAN field contains the right domain.
cc @ndhanushkodi

fix: put CF vars to unique temp dir

---

ci/pipelines/cf-for-k8s-prs.yml

If the PR pipeline takes a while to get to the step that tells GitHub
that a check is pending, it will appear to the PR submitter that there
PR has passed all checks, even if this job hasn't run yet.
This commit addresses reduces or eliminates that delay by changing two
things:
1. Have the job tell GitHub that the check is pending as the first thing
the job does. Previously, this only happened after we acquired a lock on
the environment. In some cases, it can take hours or even days to get
that lock (over a holiday weekend, for example).
2. No longer have the job run in serial. Waiting to acquire the
environment lock is enough to prevent different PRs from interfering with each
other.
Previously, we also had a 4 hour timeout on acquiring the lock. This
meant that if we couldn't get a lock …

Enable faster feedback to PR submitters that a check is pending

---

config/networking.yml

We changed the cfroutesync configuration in a way that only internal URLs are used
for uaa and capi instead of using external URLs.
For a detailed discussion see https://cloudfoundry.slack.com/archives/CFX13JK7B/p1581953775069500.
This relates also to #29. 
* Smoke test is still running using a official signed certificate
@loewenstein @achawki

Use internal addresses for uaa and capi

---

config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/istio-generated/xxx-generated-istio.yaml
config/logging.yml
config/postgres.yml
vendir.lock.yml
vendir.yml

all unencrypted requests on the mesh will now be rejected
there are two exceptions:
- capi requires an exception so that its db migrations in an init
container can still access the db before the sidecar is up
see: https://github.com/cloudfoundry/capi-k8s-release/issues/12
- log cache requires an exception because it terminates its own tls in
a way incompatible with the sidecars
1. Deploy cf for k8s
2. Enable docker support 
3. Push an app `cf push httpbin -o cfrouting/httpbin8080` 
4. Identify your service `kubectl get service -n cf-workloads -l cloudfoundry.org/app_guid=$(cf app httpbin --guid)` 
* Looks like s-GUID 
5. SSH into one of your gateways 
* `kubectl exec -it $(kubectl get pods -n istio-system | grep ingressgateway | head -n1 | awk '{print $1}') -n istio-system /bin/bash` 
6. …

feat: ensure traffic on the mesh is encrypted

---

config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-config.lib.yml
vendir.lock.yml
vendir.yml

Signed-off-by: Melena Suliteanu <msuliteanu@pivotal.io>
Adds the log cache url to capi config so logs are discoverable out of the box
https://www.pivotaltracker.com/story/show/171164346
- deploy cf-for-k8s
- install cf log cache cli
- cf tail -f <app_name> ought to work without extra configuration
@farmermel @pianohacker

bump capi-k8s-release to include log-cache url

---

config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/istio-generated/xxx-generated-istio.yaml
config/external-routing.yml
vendir.lock.yml
vendir.yml

- this will allow for easier rotation of certificates
- https://istio.io/docs/tasks/traffic-management/ingress/secure-ingress-sds/
We want to use Envoy's [Secret Discovery Service (SDS)](https://istio.io/docs/tasks/traffic-management/ingress/secure-ingress-sds/) functionality to make it easier for operators to dynamically add/rotate certs on the platform.
cf-k8s-networking story: [#171238418](https://www.pivotaltracker.com/story/show/171238418)
After this change you can observe that the `cf-system` `Gateway` is loading its certificates by the credential using SDS instead of referencing volume mounted paths.
```
k -n cf-system get gateways.networking.istio.io istio-ingressgateway -o yaml | grep credentialName | tail -n 1
```
You can also see that an additional container called …

feat: use SDS for ingressgateway cert distribution

---

config/0-min-version.star
docs/deploy.md

this allows us (rel-int) to use new ytt features without worrying too much about what version of ytt users have. note that until users upgrade to ytt 0.26.0 they will not have access to `version.require_at_least`.
after accepting this pr, if someone runs with a recently old version of ytt (eg 0.25.0) they will receive this message:
```
ytt: Error: Evaluating starlark template:
- cannot load @ytt:version: Expected to find library 'ytt', but did not find ''
in <toplevel>
4 | load("@ytt:version", "version")
```
eventually when they are on the ytt v0.26.0+, they would receive errors like this when min version is not satisfied (which is much clearer).
```
ytt: Error: Evaluating starlark template:
- version.require_at_least: ytt version '0.100.0' does not meet the minimum required version …
```

use new functionality in ytt to require min ytt version

---

ci/pipelines/cf-for-k8s.yml
docs/deploy-in-ci.md
docs/development.md
tests/smoke/smoke_test.go

Add option to skip ssl validation to smoke test.
- by default ssl validation is enabled
go test tests/smoke/...

Add option to skip ssl validation to smoke test

---

vendir.yml

as of vendir 0.8.0 we can specify minimum required version, to be used later when we want to bump for particular features.

specify min required version for vendir

---

config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/cfroutesync/cfroutesync.yaml
config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/istio-generated/xxx-generated-istio.yaml
vendir.lock.yml
vendir.yml

This updates cf-k8s-networking to include several minor updates to security and performance.
* [Operators can confirm that sidecars are not configured for app to app communication](https://www.pivotaltracker.com/story/show/171731831)
* [Operator does not have to wait for metacontroller's polling interval to see their route live](https://www.pivotaltracker.com/story/show/171737550)
* [Operator does not have to wait for cfroutesync's polling interval to see their route live ](https://www.pivotaltracker.com/story/show/171758861)
* [Operators can verify that debug endpoints on istio control plane components are inaccessible](https://www.pivotaltracker.com/story/show/171498802)
* [CF apps are accessible via HTTPS using operator-provided wildcard …

Update networking release

---

README.md
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/api_server_deployment.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/capi-kpack-watcher-deployment.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-config.lib.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-configmap.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/clock_deployment.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/deployment_updater_deployment.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/nginx-configmap.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/opi-secrets.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/service-accounts.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/service.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/worker_deployment.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/values.yml
config/capi.yml
config/kpack.yml
config/uaa.yml
config/values.yml
docs/deploy-in-ci.md
docs/deploy-local.md
docs/deploy.md
docs/example-app/package.json
docs/example-app/server.js
hack/README.md
hack/confirm-network-policy.sh
hack/generate-values.sh
hack/run-smoke-tests.sh
hack/update-gcp-dns.sh
sample-cf-install-values.yml
vendir.lock.yml
vendir.yml

🚫 We only accept PRs to `develop` branch. If this is an exception, please specify why 🚫
`cf push`! !!! 🎉 
Please merge, test it out, and give us lots of feedback!
- uses `cloudfoundry/cnb:bionic` builder image, with the buildpacks included listed [here](https://hub.docker.com/r/cloudfoundry/cnb)
- unknown scaling characteristics
- logs do not appear to stream for staging yet
- service account used for the cloud controller is currently overly-scoped as a cluster admin
- only supports apps with a single `web` process
Important: see https://github.com/cloudfoundry/capi-k8s-release#configuring-pushes-of-buildpack-apps for how to configure your k8s endpoint and registry location/creds
Handy thing: to see the progress of the staging process, check the logs of the `capi-kpack-watcher` pod.
`cf …

Add ability to cf push buildpack apps

---

config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/api_server_deployment.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-config.lib.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/values.yml
config/capi.yml
config/values.yml
hack/generate-values.sh
vendir.lock.yml
vendir.yml

🚫 We only accept PRs to `develop` branch. If this is an exception, please specify why 🚫
- Fix `log_cache` property so logs work via the `cf` cli [see
https://github.com/cloudfoundry/capi-k8s-release/pull/18]
- Remove the ability to configure the kubernetes api url - since we're
running in the cluster itself, we are fine using
`https://kubernetes.default`
- No longer need to look at current kubeconfig to determine kubernetes
api url, so removed that section of `hack/generate-values.sh`
- Enable `metric-proxy` communication instead of logcache for metrics
usage [see https://github.com/cloudfoundry/capi-k8s-release/pull/16]
https://www.pivotaltracker.com/story/show/171735462
https://cloudfoundry.slack.com/archives/CH9LF6V1P/p1584553698495500
- You should be able to see logs for an app
- You …

Bump capi-k8s-release with various enhancements

---

config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-config.lib.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/cf-autodetect-builder.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/cf-autodetect-clusterbuilder.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/service-accounts.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/values.yml
config/capi.yml
vendir.lock.yml
vendir.yml

> _Please describe the change._ 
Use namespaced kpack `Builder`
- This allows for the use of `ImagePullSecrets` for the builder image, which is not allowed for the previous `CustomBuilder`-type builder
- Moves kpack builds to their own namespace - defaulted to `cf-workloads-staging`, where the builder also lives
- Update ccng image to take this into account
---
- Let us know if getting this merged is urgent.
_Special notes for your reviewer /  **Acceptance Criteria** (if applicable)_
`cf push` should still work :)
_Resources_
> _Include any links to other PRs, stories, slack discussions, etc... that will help establish …

Bump capi to use namespaced kpack `Builder`

---

config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-config.lib.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/values.yml
vendir.lock.yml
vendir.yml

> _Please describe the change._ 
Directly pass through `kpack.registry.hostname` to kpack's
`Image.spec.tag` property.  This allows dockerhub to be used as a registry for images built by
kpack.  See the updated documentation for examples: https://github.com/cloudfoundry/capi-k8s-release#configuring-pushes-of-buildpack-apps
Fixes https://github.com/cloudfoundry/cf-for-k8s/issues/71
---
- Let us know if getting this merged is urgent.
> **_Example Acceptance Criteria:_**
both dockerhub and gcr should still work as image destinations

Bump capi to enable dockerhub use

---

config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/values.yml
vendir.lock.yml
vendir.yml

This is to support staging logs being shown by the cli when pushing an app
See https://github.com/cloudfoundry/cf-k8s-logging/issues/18
> _Please describe the change._ 
kpack build pods now have the label `cloudfoundry.org/source_type=STG`.  This will allow the logging framework to set the source type on log envelopes containing the output of builds.  The cli will then be able to display these logs during a push.
I believe that there will also have to be a change to the logging infrastructure before the source type will be set and we'll actually see push logs via the cli. (cc @pianohacker)
---
_Resources_
Two slack threads,
one large: https://cloudfoundry.slack.com/archives/CH9LF6V1P/p1584638456029000
and one small: https://cloudfoundry.slack.com/archives/CH9LF6V1P/p1585175250043300
_Tag …

Bump capi to label build pods with source_type STG

---

config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/istio-generated/xxx-generated-istio.yaml
config/external-routing.yml
vendir.lock.yml
vendir.yml

**Please describe this change**
- now deploys one ingressgateway per node [#171067809](https://www.pivotaltracker.com/story/show/171067809)
- in demos, users can now hit any one of the nodes to get the full
ingressgateway experience
- in production, operators can set up hardware load balancers to
balance between node ips
also featuring:
- minor updates to security policies to ensure kube-api-server has
network access to the istio-sidecar-injector. See:
https://github.com/cloudfoundry/cf-for-k8s/issues/69 and
[#171877759](https://www.pivotaltracker.com/story/show/171877759)
**GIVEN** I have deployed a cloud foundry
**WHEN** I `curl -H host:api.<cf-domain> <node ip>`
**THEN** I see some delicious json from capi
**GIVEN** I have deployed an app to my cloud foundry …

Update cf-k8s-networking: IngressGateway Daemonset & NetworkPolicy Fixes

---

hack/update-gcp-dns.sh

When we run `nslookup "*.$DNS_DOMAIN"`, our output includes the following line:
`Address:	10.35.30.10#53`
This causes the script to hang forever, since it should ignore that Address line.
This change excludes that line.

Change update-gcp-dns.sh to exclude 'Address' with # in addition to :

---

config/_ytt_lib/github.com/cloudfoundry/metric-proxy/LICENSE
config/_ytt_lib/github.com/cloudfoundry/metric-proxy/config/manifests/100-metric-proxy-service-account.yml
config/_ytt_lib/github.com/cloudfoundry/metric-proxy/config/manifests/400-metric-proxy-service.yml
config/_ytt_lib/github.com/cloudfoundry/metric-proxy/config/manifests/50-metric-proxy-secrets.yml
config/_ytt_lib/github.com/cloudfoundry/metric-proxy/config/manifests/500-metric-proxy-deployment.yml
config/_ytt_lib/github.com/cloudfoundry/metric-proxy/config/values.yml
config/capi.yml
config/metrics.yml
config/values.yml
hack/generate-values.sh
sample-cf-install-values.yml
tests/smoke/smoke_test.go
vendir.lock.yml
vendir.yml

Signed-off-by: Caitlyn Yu <cyu@pivotal.io>
Signed-off-by: David Timm <dtimm@pivotal.io>
This uses the [metrics-proxy](https://github.com/cloudfoundry/metric-proxy) to return metrics for `cf push` and `cf app`. The metric-proxy makes a request to the Kube API and formats the results to match the existing log-cache API.
**_Acceptance Criteria:_**
**Given** I've deployed cf-for-k8s with this branch
**When** I run `kubectl get pod -n cf-system | grep metric-proxy`
**Then** I see the metric-proxy pod is running
**Given** I've deployed cf-for-k8s with this branch
**When** I run `cf push <my-app>` ie `cf app <my-app>`
**Then** I see cpu and memory metrics listed in the output.
For more information, see our [README](https://github.com/cloudfoundry/metric-proxy/blob/master/README.md)
_Tag your …

Integrates metric-proxy to return app metrics

---

build/postgres/init-db-values.yml
config/_ytt_lib/postgres/rendered.yml
config/postgres.yml

>
Use a Secret to store DB init credentials instead of interpolating them directly into the init.sh ConfigMap.
---
_please provide a series of instructions (eg kubectl or cf cli commands) for how our Product Manager can verify that your changes were properly integrated_
1. …

Use a Secret to store DB init credentials

---

config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/istio-generated/xxx-generated-istio.yaml
vendir.lock.yml
vendir.yml

Fixes the issue mentioned in https://github.com/cloudfoundry/cf-for-k8s/issues/102
- DaemonSets don't have a field called "maxSurge"
- `MaxUnavailable` was updated to 1 to match the Gorouter behavior during an upgrade.
- DaemonSets have "updateStrategy" instead of "update"
> Is there anything else of note that the reviewers should know about this change?
Just that it fixes this [issue](https://github.com/cloudfoundry/cf-for-k8s/issues/102)
**GIVEN** I have deployed a cloud foundry
**WHEN** I describe the ingress gateway  DaemonSet with `kubectl -n istio-system describe daemonset istio-ingressgateway`
**THEN** I see the spec contains the following [keys](https://github.com/cloudfoundry/cf-for-k8s/blob/203525be553553253daaf8af0809d85 …

Correct DaemonSet spec.updateStrategy

---

config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/api_server_deployment.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-config.lib.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/values.yml
vendir.lock.yml
vendir.yml

Add statsd-exporter container to capi-api-server
This translates the metrics ccng emits via statsd to a
prometheus-scrapable format.
Also annotate the capi-api-server pod with prometheus annotations so
that it will be scraped.
---
There should no longer be a bunch of connection refused errors in the `capi-api-server` logs.  When you open a shell onto a `capi-api-server` pod, you should be able to
```
curl localhost:9102/metrics | less
```
And see a bunch of capi metrics
@cloudfoundry/cf-capi @hev @kkburr

Make CAPI stats scrapable by prometheus

---

hack/update-gcp-dns.sh

> _Please describe the change here._
A refactor of the DNS update script for GCP, fixing some logic:
- Don't attempt to to update if the LB address is already correct in DNS.
- Don't attempt to delete a record if it doesn't exist already.
- Add some functions to make things a little more readable.
---
Yes.
Just tryinig to make this script a bit more readable/functional.
_please provide a series of …

Refactor DNS update utility.

---

config/values.yml

This is a simple bump to the desired `cfroutesync` image to include recent changes such as:
- basing the image off of `cloudfoundry/run:tiny`
- reducing unnecessary requests to the Cloud Controller API (CAPI)
> Is there anything else of note that the reviewers should know about this change?
No
_please provide a series of instructions (eg kubectl or cf cli commands) for how our Product Manager can verify that your changes were properly integrated_
**GIVEN** I have deployed a cloud foundry
**WHEN** I describe the cfroutesync deployment with `kubectl -n cf-system describe deployment/cfroutesync`
**THEN** I see the container spec specifies `gcr.io/cf-networking-images/cf-k8s-networking/cfroutesync@sha256:3b2b25614d6da572175a848003e3798 …

bump `cfroutesync` image digest

---

config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-config.lib.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/values.yml
vendir.lock.yml
vendir.yml

```
Bump capi-k8s-release:
e6dc30d Jaskanwal Pawar: Bump default CCNG docker image reference
e861b64 Jaskanwal Pawar: Increase frequency of diego_sync for cf6+v2 push
423f871 Chris Selzo: Add statsd-exporter container to capi-api-server
00ac3ec Chris Selzo: Bump CC source to fix `cf6 push`
97f0fbe Aakash Shah: Update build script to account for new Dockerfile location
64c2dab Renee Chu: Copy watcher source code to eventual image
a8b1df9 Aakash Shah: Update Dockerfile to reflect that watcher source code is within repo's `src/capi
4cd4f8f Renee Chu: Move watcher Dockerfile to be under watcher directory
c41f5bf Renee Chu: Create symlink to watcher Dockerfile
Bump cloud_controller_ng:
82dbf8abe Chris Selzo: Add kpack lifecycle support in process sync
6a6638497 George Blue: V3 client can …
```

Bump capi-k8s-release: fix cf6 push

---

docs/deploy.md

Remove diego_docker flag instruction since we don't need that anymore.
cf push without enabling Diego docker flag works.

Remove diego docker flag instruction

---

docs/deploy-local.md

The previous minikube instructions didn't work with `vcap.me` as the domain. I've updated the instructions to use [nip.io](https://nip.io/).
---
_please provide a series of instructions (eg kubectl or cf cli commands) for how our Product Manager can verify that your changes were properly integrated_
> _It's helpful to tag a few other folks on your team or your team …

Update minikube instructions

---

config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/LICENSE
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/api_server_deployment.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccdb-migrate-job.yaml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-config.lib.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/cf-autodetect-builder.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/values.yml
config/postgres.yml
vendir.lock.yml
vendir.yml

- CC's DB migration logic should now support strict mTLS with the DB's
sidecars
- Create one kpack image per app not build 
- Merge pull request #30 from evanfarrar/add-license -- adds apache license
- Fix internal_hostname for CC API
- Revert "Opi docker custom port" (cloudfoundry/revert-1558-opi-docker-custom-port)
- bump ccng to include the above changes
Tracker Stories:
https://www.pivotaltracker.com/story/show/171388449
https://www.pivotaltracker.com/story/show/171851581
https://www.pivotaltracker.com/story/show/172212215
https://www.pivotaltracker.com/story/show/172246299
https://www.pivotaltracker.com/story/show/172322578
---
cc: @reneighbor @jspawar @selzoc @aashah @sethboyles

Db migration with sidecars

---

config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/values.yaml
config/values.yml
vendir.lock.yml
vendir.yml

[#172087151](https://www.pivotaltracker.com/story/show/172087151)
Related to [this issue](https://github.com/cloudfoundry/cf-k8s-networking/issues/36), we now pin the cfroutesync image digest in cf-k8s-networking, so we can remove the override for the image url in cf-for-k8s values. 
**GIVEN** I have deployed a cloud foundry
**WHEN** I describe the cfroutesync deployment with kubectl -n cf-system describe deployment/cfroutesync
**THEN** I see the container spec specifies `gcr.io/cf-networking-images/cf-k8s-networking/cfroutesync@sha256:c54be4b33f6a8a7a6dc24ee74cff468b3484411b64182d866a5be52cd67425a4`
@christianang 

Pin cfroutesync image digest in cf-k8s-networking

---

config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/crd/networking.cloudfoundry.org_routes.yaml
config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/values.yaml
config/values.yml
vendir.lock.yml
vendir.yml

This PR includes the Route CRD that will be referenced by the Cloud Controller and the future routecontroller component from the cf-k8s-networking team.
---
This PR is a follow-up PR to the bump made as part of #151 . Until that PR is merged, this diff will look messy and misleading. To see what we've added as part of just this PR before that is merged, click on [this link](https://github.com/cloudfoundry/cf-for-k8s/compare/pin-cfroutesync-digest...pr-include-route-crd).
See [this slack thread](https://cloudfoundry.slack.com/archives/CFX13JK7B/p1587675432112300) for more context on why this CRD is needed urgently. Basically, we won't be able to bump capi-k8s-release in cf-for-k8s until this CRD is available in cf-for-k8s. For broader context on the general routecontroller work, see this …

Include Route CRD

---

config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/deployment.star
config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/deployment.yml
config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/secrets/admin_client_credentials.yml
config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/uaa.lib.yml
config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/values/_values.yml
config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/values/image.yml
config/uaa.yml
vendir.lock.yml
vendir.yml

I'm creating this PR to make it easy to share the changes we needed to make with the UAA team. (And to show the general process for bumping a component in cf-for-k8s.)
The [first commit](https://github.com/cloudfoundry/cf-for-k8s/commit/8cb3a6d3f9ecb32857b3a260d4efda4ec811de22) shows step 1: bumping the commit/release in `vendir.yml`
The [2nd commit](https://github.com/cloudfoundry/cf-for-k8s/commit/0e9c444a7bc99b4490adf551e4d89a18d3bd1f95) shows the changes that came in from running `vendir sync`
The [3rd commit](https://github.com/cloudfoundry/cf-for-k8s/commit/2c0019d49b2875a4e663dd9b0c407e409a091c73) shows the changes we needed to make to `config/uaa.yml` 
---
- Checkout the [contributing …

bump to UAA from 74.16 > 74.17

---

config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/crd/networking.cloudfoundry.org_routes.yaml
config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/values.yaml
vendir.lock.yml
vendir.yml

This PR bumps the cf-k8s-networking component. The effect of this bump is to make the Route CRD no longer cause problems when updating an existing cf-for-k8s environment with `kapp`.
(Copied from tracker story [#172569406](https://www.pivotaltracker.com/story/show/172569406))
The `Route` CRD has an empty top level `status` section in its definition which causes lifecycle problems with `kapp`.
https://github.com/cloudfoundry/cf-k8s-networking/blob/63b8a02d2ec88e5b21479d92cfa266d28dd5cc67/routecontroller/config/crd/bases/networking.cloudfoundry.org_routes.yaml#L125-L130
It will deploy successfully initially, but on upgrades may have failures because `kapp` will try and reconcile the CRD to have an empty status.
```
kapp deploy -a test -f …
```

Bump cf-k8s-networking to fix reconcile problem with Route CRD

---

config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccdb-migrate-job.yaml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-config.lib.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/service-accounts.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/worker_deployment.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/values.yml
vendir.lock.yml
vendir.yml

>
Sai mentioned potentially cutting a 0.2.0 release and we pointed out that CAPI hasn't been bumped in a couple weeks.
This includes:
- a fix for a regression/bug where org deletion got busted
- https://github.com/cloudfoundry/capi-k8s-release/pull/33 which completes [#171007126](https://www.pivotaltracker.com/story/show/171007126), making sure CAPI communication uses all internal DNS (it wasn't for loggregator)
---
- Include any links to related PRs, issues, stories, slack …

ENH: bump CAPI to current head of master

---

config/0-min-kapp-version.yml
docs/deploy.md

>
Kapp versions `0.24.0+` are required to deploy `cf-for-k8s` as of some recent changes, so just want to update that prerequisite
---
Confirm that using at least `kapp` version `0.24.0` you can deploy with the existing deployment instructions
Stemming from this conversation: https://cloudfoundry.slack.com/archives/CH9LF6V1P/p1588698073226400

Update deploy docs with updated kapp requirements

---

config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/istio-generated/xxx-generated-istio.yaml
config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/values.yaml
vendir.lock.yml
vendir.yml

We were not exposing the port that Istio Pilot uses for its metrics endpoint in our `NetworkPolicy` which resulted in Prometheus being unable to scrape it.
This `cf-k8s-networking` bump includes changes from https://github.com/cloudfoundry/cf-k8s-networking/pull/39 to fix this.
[Tracker story #172313646](https://www.pivotaltracker.com/story/show/172313646)
1. Deploy these changes
1. Confirm that the `pilot-network-policy` `NetworkPolicy` is allowing ingress on port `15014`:
```
kubectl get -n istio-system NetworkPolicy/pilot-network-policy -o yaml
```
3. If you'd like you can also `kubectl exec` on to a pod that has `curl` and `curl istio-pilot.istio-system:15014/metrics` and marvel at the output.
@jrussett has crafted a premium command for doing this:
```console …
```

Expose Istio Pilot metrics port in NetworkPolicy

---

hack/app-registry-check-dockerfile/Dockerfile
hack/validate-registry-access.sh

If these credentials are misformatted or invalid, you may not find out until after the kapp deploy finishes and you try to push an app.
The idea here is that you can run this script upfront to validate the credentials and tighten this feedback loop.
Known issues / future enhancements
- This commits a minimal Dockerfile to the repo, which likely is not necessary.
- This pushes a docker image to a repository and doesn't fully clean up after itself.
- This cannot yet handle Azure container registry (only docker and gcr)
```
$ hack/validate-registry-access.sh --help
...
Confirm that app_registry credentials have push access to the specified repository.
usage:
app_registry_check.sh <yaml with app_registry configuration>
```
---
- Checkout …

ENH: add hack script for validating app_registry credentials

---

docs/contributing.md

We were getting the following smoke tests failures. Updating the environment variable fixed the issue. CC @louis-brann 
```
• Failure [194.274 seconds]
Smoke Tests
/home/pivotal/workspace/cf-for-k8s/tests/smoke/smoke_test.go:31
when running cf push
/home/pivotal/workspace/cf-for-k8s/tests/smoke/smoke_test.go:32
creates a routable app pod in Kubernetes from a source-based app [It]
/home/pivotal/workspace/cf-for-k8s/tests/smoke/smoke_test.go:127
Timed out after 120.000s.
Expected
<int>: 404
to equal
<int>: 200
/home/pivotal/workspace/cf-for-k8s/tests/smoke/smoke_test.go:146
Summarizing 2 Failures:
[Fail] Smoke Tests when running cf push [It] creates a routable app pod in Kubernetes from a docker image-based app
/home/pivotal/workspace/cf-for-k8s/tests/smoke/smoke_test.go:107
[Fail] Smoke …
```

Change env variable to fix smoke tests

---

config/_ytt_lib/github.com/cloudfoundry/metric-proxy/config/manifests/500-metric-proxy-deployment.yml
config/_ytt_lib/github.com/cloudfoundry/metric-proxy/config/values.yml
vendir.lock.yml
vendir.yml

Fixes: https://github.com/cloudfoundry/cf-for-k8s/issues/177
* update metric-proxy app selector to match on `guid` (process guid sent from capi) rather than `app_guid`
[#172771099]
Signed-off-by: Louie Brann <lbrann@pivotal.io>
**Relevant Links**
* Tracker Story: https://www.pivotaltracker.com/story/show/172771099
* Passing pipeline: https://loggregator.ci.cf-app.com/teams/main/pipelines/metric-proxy/jobs/run-tests-on-cf-for-k8s-pr/builds/16
* Slack conversation: https://cloudfoundry.slack.com/archives/CH9LF6V1P/p1588969711283900
1. `cf7 push <your app> --strategy rolling` -->this does not show accurate metrics because of a known kubeapi delay
1. `cf7 app <your app>` --> this will show metrics after the delay (~30 seconds)
1. `cf7 push <your app> --strategy rolling` …

[Bug Fix] cf7 push --strategy rolling shows metrics

---

ci/dockerfiles/cf-for-k8s-ci/Dockerfile
config/0-min-kapp-version.yml
config/kapp-rebase-rules.yml
tests/configs/configs_test.go
tests/configs/go.mod
tests/configs/go.sum

Add a `--validate` flag to install-cf.sh so we can validate k8s resources.
Use `--validate` to test PRs.
Solves https://github.com/k14s/kapp/issues/98  
~This is WIP because kapp's `Config` resource does not play well with kubeval.~
Introduce an error somewhere in the `config` folder and execute `install-cf.sh --validate` to see if it is caught.

Add validation with kubeval

---

hack/generate-values.sh

Co-Authored-By: Mark Stokan <mstokan@pivotal.io>
We would like to be able to silence the generate-values hack warning message so that messaging doesn't confuse users of vendor distributions.
The default behavior should be preserved.
```gherkin
When I run ./hack/generate-values.sh -d test -s
I shouldn't see the hack warning message
```
@cloudfoundry/pcf-release-engineering

add option to omit hack warning message

---

config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/values.yml
vendir.lock.yml
vendir.yml

Signed-off-by: Travis Patterson <tpatterson@pivotal.io>
Upgrade logging to 0.2.1 for osl
---
the images should now have osl information
@pianohacker @MasslessParticle @JSchuenke

upgrade logging to 0.2.1

---

config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/values.yaml
vendir.lock.yml
vendir.yml

The new images include a label describing the repository and commit SHA that the image is built from
[#172922921](https://www.pivotaltracker.com/story/show/172922921)
---
**When** I run `docker inspect <IMAGE>`, replacing `<IMAGE>` with the cfroutesync image that's deployed as part of cf-for-k8s.
**Then** I can see a label called "io.pivotal.metadata" with information describing the dependencies packaged into the image, including the github repository and commit SHA used to build the image
Note: The "io.pivotal.metadata" label is temporary and due to the tooling we're using at the moment. We plan to update this label to be more vendor agnostic as soon as we can get the tooling changes and a standardized label for cf-for-k8s. …

bump networking images

---

config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/api_server_deployment.yml
config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/values/images.yml
vendir.lock.yml
vendir.yml

also bumps images to the most recent set that've passed CAPI's CI.
https://cloudfoundry.slack.com/archives/C07C04W4Q/p1590092485340200?thread_ts=1590008371.325800&cid=C07C04W4Q
Check that a deployed cf-api-server pod has a readiness check. If you want to confirm that it's working, configure the cf-api-server to listen on a port other than 80 to see the readiness check fail.
at @jamespollard8 's request.

bump capi to pick up api readiness check

---

docs/deploy.md

Fixes #209.
[#173021567](https://www.pivotaltracker.com/story/show/173021567)
Co-authored-by: Joseph Palermo <jpalermo@pivotal.io>
Updates the docs to reflect an alternate source of external ip information for domain based loadbalancer services. See the warning block on [istio docs](https://istio.io/docs/tasks/traffic-management/ingress/ingress-control/) and the loadbalancer service status api definition in the[ kubernetes api reference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#loadbalanceringress-v1-core).

Update docs for hostname based loadbalancer service

---

config/capi.yml
config/eirini.yml
config/uaa.yml
config/values.yml
hack/generate-values.sh
sample-cf-install-values.yml

This PR separates the TLS certificate used for system, workloads and internal endpoints into three, distinct, certificates. Hopefully, this will clarify what each certificate is used for, as well as provide validation that each certificate is only being used for its intended purpose since each certificate now only has the required domains associated with it.
---
* Deploy with these changes as normal
* Open …

Explicitly define separate system, workloads and internal certs

---

docs/deploy.md
docs/setup-ingress-certs-with-letsencrypt.md

- Update deploy docs to use `https` protocol when testing the app is reachable.
- Add docs to setup ingress certs with lets encrypt
_credit to relint team in putting the instructions together_
**Why it is needed**
A number of people in slack threads are sharing the story [ingress https](https://www.pivotaltracker.com/story/show/172758668) on how to setup https instructions. The new doc will make https how-to a first class citizen in our docs. 
- After following steps to setup https, I can access the app with https.
@paulcwarren @davewalter @jamespollard8 FYI

Add docs on how-to setup https

---

config/kpack.yml
config/networking.yml

- new namespaces except istio-system have istio injection enabled by
default
- Add exception for kpack-webhook since istio strict TLS does not work
for communication between apiServer and webhooks
[#172880857](https://www.pivotaltracker.com/story/show/172880857)
Co-authored-by: Joseph Palermo <jpalermo@pivotal.io>
Co-authored-by: Lisa Burns <lcho@pivotal.io>

Add additional namespaces to istio mesh

---

config/external-routing.yml
config/gateway.lib.yml

This PR renames the system certificate from `istio-ingressgateway-certs` to `cf-system-cert`. This is to support hot reloading of certificates when the secret changes. For some reason Istio doesn't hot reload certificates if the Kubernetes secret name begins with `istio`. The only reference I could find to this in their documentation is in a note [here](https://istio.io/docs/tasks/traffic-management/ingress/secure-ingress/#configure-a-tls-ingress-gateway-for-a-single-host), but it doesn't really explain why. It seems best to change it to a new name that doesn't start with `istio` and as a bonus this will also keep it consistent with the `cf-workloads-cert` secret name.
Related tracker story [#173181160](https://www.pivotaltracker.com/story/show/173181160).
---
_please …

Rename system certificate secret to cf-system-cert

---

.gitignore
docs/deploy-in-ci.md
docs/deploy-local.md
docs/deploy.md
tmp/.gitignore

/tmp is ephemeral storage on most *nix system and a security risk on all
This updates the most common deploy instructions to use `./tmp` instead which
is excluded via `.gitignore`.
There's still an alarming amount of `/tmp` in use but this is a start.
Signed-off-by: Paul Czarkowski <username.taken@gmail.com>
>
---
- Is there anything …

Change docs to use ./tmp instead of /tmp

---

ci/tasks/install-cf-on-kind/task.sh
config-optional/add-metrics-server-components-v0.3.6.yml
config-optional/add-metrics-server-components.yml
config-optional/patch-metrics-server.yml
deploy/kind-on-gcp/install-and-test.sh
docs/deploy-local.md
docs/deploy.md
hack/generate-values.sh
tests/configs/configs_test.go
tests/configs/go.sum
vendir.lock.yml
vendir.yml

This PR allows providing metrics-server on clusters that don't provide it.
`metric_proxy` requires `metrics-server` to function, but not all IaaSes provide the metrics-server, so this change allows operators to include metrics-server on IaaSes that don't already provide it: (e.g. EKS, kind, minikube) using a config-optional file.
---
Relevant stories/issues:
- https://www.pivotaltracker.com/story/show/172821078
- https://www.pivotaltracker.com/story/show/172771099  
- https://www.pivotaltracker.com/story/show/172319933
- https://github.com/cloudfoundry/cf-for-k8s/issues/210#issue-625110008
- https://github.com/cloudfoundry/cf-for-k8s/issues/177 
- https://github.com/cloudfoundry/cf-for-k8s/issues/123 
In an IaaS without a metrics-server (e.g. EKS),  include …

Optionally include metrics-server

---

config/uaa.yml
config/values.yml

Co-authored-by: Ulrich Kramer <u.kramer@sap.com>
>
If case of using an external database for uaa (e.g. RDS), using tls is important for obvious reasons. By setting the ca cert which is used to verify the certificate of the database server, tls will be enabled. Using an external database without a ca certificate will still unencrypted communication.
- Include any links to related PRs, issues, stories, slack discussions, etc... that will help …

Enable tls for external uaa

---

docs/configuration/setup-ingress-certs-with-letsencrypt.md

You can now set up ingress certs before or after cf-for-k8s installation
Follow the instructions and you are able to setup ingress certs with lets-encrypt.

Update instructions for generating real certs

---

config/uaa.yml

* Allows for downstream overlays to safely append to the list of default scopes granted to a newly created UAA user, instead of being holding downstream overlays responsible for owning the default list.
* Copy of #244. Includes the feedback from that PR (I totally thought there was no diff...)
---
1. Deploy old cf-for-k8s
1. Using uaac, collect the list of scopes granted to a newly created user (`uaac user get <>`).
1. Deploy new cf-for-k8s
1. Using uaac, observe the list of scopes granted to a newly created user has not changed.

Explicitly copy/paste default scopes for user

---

config/capi.yml
config/fix-db-startup-order.yml
config/postgres.star
config/postgres.yml
config/uaa.yml
config/values.yml

>
If external databases are used for capi and uaa, there is no need to install an internal one. Only if at least one is not using `hostname` to specify a database host, we install an internal one and use its hostname.
For documentation on external databases, see
https://github.com/cloudfoundry/cf-for-k8s/pull/143
- Is there anything else …

Do not install cf-db if external databases are used for capi and uaa

---

config/capi.yml
config/values.yml

Set the ca_cert value introduced in the capi release.

Enable tls for external capi database

---

config/gateway.lib.yml
config/gateway_test.star

* Full wildcard was recommended by the Networking team in #238
* Allows SSL traffic to apps deployed to the system domain
* Apps deployed to the workloads namespace will continue to use the
workloads certificate.
* Copy of #242
---
I listed out acceptance in #238.
@weymanf

Apply ssl for system domain workloads

---

.github/PULL_REQUEST_TEMPLATE.md

The current [URL](https://github.com/cloudfoundry/cf-for-k8s/blob/develop/docs/contributing.md) leads to a 404.

fix outdated URL in PR-template

---

ci/pipelines/cf-for-k8s.yml

This uses the bitnami postgresql helm-chart to install a database into the same cluster, otherwise it is a duplicate of the existing job "validate-cf-for-k8s-gke".
First step to implement proposal #168

Add additional ci-job to validate external database feature

---

tests/configs/configs_test.go

Update the timeout threshold on the kubeval unit test. We're seeing timeouts in the CI jobs for updating releases likely due to hardware differences with our dev machines.
See the failures linked in these tracker stories:
https://www.pivotaltracker.com/story/show/173863620
https://www.pivotaltracker.com/story/show/173863619
Go into the config tests suite and run Ginkgo. (Or just run all of the unit tests with Ginkgo). The tests should continue to pass and not take any longer aside from the apparent time creep from actual code updates that lead to the timeout issues.
`ginkgo -r` or `ginkgo ./...` in the `tests/` directory 
cc @ericpromislow

Update kubeval timeout threshold

---

config/capi.yml
config/uaa.yml
config/values.yml
hack/generate-values.sh
sample-cf-install-values.yml

[finishes #173295725](https://www.pivotaltracker.com/story/show/173295725)
fixes #233
Co-authored-by: Dave Walter <dwalter@pivotal.io>
Co-authored-by: Andrew Wittrock <awittrock@pivotal.io>
Use separate secret values for each of the clients we create in UAA.
Run the hack/generate-values.sh script to generate the new additional secret values. Then follow the standard ytt and kapp deploy flow described in the deploy.md doc.
When your cf-for-k8s has deployed successfully, check that smoke tests continue to run and that the configMaps no longer have duplicate secret content.
cc @Birdrock 

Use separate secret values for uaa client secrets

---

config/capi.yml
config/values.yml
hack/generate-values.sh
sample-cf-install-values.yml

[#173930784](https://www.pivotaltracker.com/story/show/173930784)
Adds a separate secret for the db encryption key for capi to consume when they're ready to move away from the sensitive plaintext data in the ConfigMap. Note that this reference is not yet consumed. See https://github.com/cloudfoundry/cf-for-k8s/pull/289 for the initial pass where we missed this as a piece of sensitive information configured in plaintext.
Deploy cf-for-k8s as normally and validate that the smoke test continues to pass.
cc @Birdrock

Add separate secret for capi cf db encryption key

---

config/uaa.yml

DO NOT MERGE. Only merge after #295, which we split out into a separate pr make the refactor more digestible. May require another rebase due to changes made in that PR.
[finishes #173295381](https://www.pivotaltracker.com/story/show/173295381)
[finishes #173930701](https://www.pivotaltracker.com/story/show/173930701)
fixes #231 #232 
Template client secrets into Secret resources and mount them onto the UAA deployment instead of passing the info through plaintext values on the ConfigMap. This is a security-focused refactor and should not affect functionality.
Deploy cf-for-k8s as normally according to the deploy.md docs. Verify that the deployment succeeds and the smoke test continues to pass.
cc @Birdrock

Uaa secrets

---

config/capi/_ytt_lib/capi-k8s-release/templates/controllers_deployment.yml
config/capi/_ytt_lib/capi-k8s-release/templates/service-accounts.yml
config/capi/_ytt_lib/capi-k8s-release/values/_default.yml
config/capi/_ytt_lib/capi-k8s-release/values/images.yml
config/capi/capi.yml
config/uaa/uaa.yml
config/values.yml
hack/generate-values.sh
vendir.lock.yml
vendir.yml

We'd like to rename the capi-kpack-watcher deployment to "cf-api-controllers" to match some new source code organization we've done in capi-k8s-release. In cf-for-k8s, the main thing that still bears that name is the client secret. 
This PR does change one left-hand-side key in `values.yml`, and also updates hack/generate-values to match.
- we are doing this rename in accordance with https://github.com/cloudfoundry/capi-k8s-release/blob/rename-kpack-watcher-to-controllers/decisions/0003-cf-api-controller-repo.md
**PLZ NOTE:**
This PR uses a branch of capi-k8s-release that has the full rename. When this is merged, we'll need to merge that branch or else automated bumps of capi-k8s-release will cause cf-for-k8s pipeline breakage. Can we rely on cf-for-k8s autobump automation magic to change …

rename kpack-watcher-client-secret to cf-api-controllers-client-secret

---

config/kpack/_ytt_lib/kpack/kpack-rendered.yml
vendir.lock.yml
vendir.yml

Additional notes about this change can be found in this Tracker story: [#173992907](https://www.pivotaltracker.com/story/show/173992907)
Co-authored-by: Andrew Costa <acosta@pivotal.io>
---
- Is there anything …

MAINT: temporarily use kpack from commit d3004be to unblock CAPI

---

docs/deploy.md
docs/platform_operators/external-databases.md

We added documentation on how to use an external database (AWS RDS) with cf-for-k8s.
When I follow the instructions in the document
Then I'm able to setup my cf-for-k8s with an external database without debugging or further exploration
@kramerul, @loewenstein

Add documentation for external RDS database

---

config/z-kapp-versioned-creds.yml

it is reference by a Role which kapp does not support yet.
https://github.com/k14s/kapp/issues/128
Co-authored-by: Gary Liu <garyliu@vmware.com>
Co-authored-by: James Pollard <jpollard@pivotal.io>
>
---
- Checkout the [contributing …

do not kapp version kpack webhook-certs secret

---

ci/pipelines/cf-for-k8s.yml
ci/tasks/install-cf-on-gke/task.sh
ci/tasks/install-cf-on-gke/task.yml
ci/tasks/install-postgres/task.sh
ci/tasks/install-postgres/task.yml

Add a check for external DB functionality to pull request checks in the concourse pipeline (#168)
We could not test this on our concourse. Integrations and configurations for GCP are missing.
Acceptance Steps*
Update Concourse Pipeline and see if new pull request steps are working
See also #291
@lucaschimweg @modulo11

Add external db check on pr to ci pipeline (second try)

---

config/kpack/kapp-order.yml
config/kpack/kapp-wait-rules.yml

Add kapp wait rule ([docs here](https://github.com/k14s/kapp/blob/develop/docs/config.md#wait-rules)) configuration for CRDs from kpack to provide deploy-time feedback on things like bad builder configuration without having to look through the statuses of the resources after kapp reports a successful deploy. Add a kapp change group ([docs here](https://github.com/k14s/kapp/blob/develop/docs/apply-ordering.md)) to compensate for the dependency of our kpack builder on the stack and store to which it refers. 
* Kapp authors confirmed that a single top level timeout config applies to everything, so if any single resource reconciliation takes longer than the global timeout threshold, you get a timeout error. ~~I'm not sure whether the wait rule allows specifying a more granular …

ENH: Add kapp wait rules for kpack resources

---

ci/pipelines/cf-for-k8s-contributions.yml

Currently the status of builds related to external database jobs are reported with the same context as other tests.
This PR will fix this.
This came up, because the reason for the failure of #336 was not clear.
We have no experience with the status reporting in github. We suppose that before merging this PR, you need to [create a new status for github](https://developer.github.com/v3/repos/statuses/).
* Create status in github
* Merge PR
* Apply new pipeline
@modulo11 
CC: @Syerram

Fix status context for external-db pipeline jobs

---

config/uaa/uaa.yml
config/values.yml
hack/generate-values.sh
sample-cf-install-values.yml

Enhancement/Refactor: Move plaintext secrets from the uaa config map into kubernetes secrets and mount them on the uaa deployment.
Replaces the previously deleted login saml provider cert, as we found out that the functionality cannot be disabled and could present a vulnerability.
Fixes #229, #230.
**Open Questions**
- Do we have any user-facing requirements for the actual contents of the config map in the final rendered yaml file?
- I've added some overlay removes to eliminate some default placeholder values under the assumption that we don't want to mislead users into thinking the ConfigMap is the final source of information on that configuration when the secret contents are actually being merged in from the mounted volumes.
- Do we need to also add a second encryption …

Move UAA encryption keys and login info to secrets

---

ci/pipelines/cf-for-k8s-stability-tests.yml

Now that we have a wavefront account, start pushing a metric there from our long-lived-sli, which runs smoke test every 20 minutes.
**Open Questions**
Do we have any particular naming conventions in mind? Currently each of the metric fields is filled in with fairly generic info.
After running https://release-integration.ci.cf-app.com/teams/main/pipelines/cf-for-k8s/jobs/long-lived-env-sli/builds, see the metric available in our wavefront account.
cc @nhsieh and @cloudfoundry/cf-release-integration

Push long lived env sli metric

---

config/kapp-ordering.yml

- log-cache depends on UAA and currently its crash loop backoff slows our 5 minute deploys by about a minute on average
- now, kapp will only attempt to deploy log-cache once UAA is up
more conversation on this lives in [this slack thread](https://cloudfoundry.slack.com/archives/CUW93AF3M/p1596240135287400) as well as [this more meta discussion on the topic in #cf-for-k8s](https://cloudfoundry.slack.com/archives/CH9LF6V1P/p1595869988036400)
before = cf-for-k8s develop (less ordering)
after = this branch
(units: minutes:seconds)
average: 5:02 -> 4:04
best: 4:44 -> 3:52
worst: 5:21 -> 4:13
roughly 21% decrease in deploy times
Log Egress team has a [placeholder] story for dealing with this in a more "kubernetes native" way here: https://www.pivotaltracker.com/story/show/174155076
---
- Make …

FEAT: speed up deploys by adding kapp ordering for log-cache

---

docs/platform_operators/external-databases.md

duplicate code block markdown removed.
---
The string "bash" should no longer appear in rendered document.

remove duplicate formatting strings

---

config/capi/capi.yml

CAPI is currently adding support to consume credentials from secrets and requires that the values of the names of these secrets to be passed through first.
Doing in accordance with the recommendations for credentials in cf-for-k8s from here: https://docs.google.com/document/d/1VKMVaBcIUjro_y38KwMskvqoqSXljqVcLA_CVPTHbXU/edit#
---
1. Deploy cf-for-k8s
1. Ensure nothing has broken (shouldn't have since this is purely additive and the version of CAPI underneath remains unchanged/will not care about these new values)
Thanks,
Jwal + @matt-royal

Pass through values for secret names for CAPI

---

config/capi/_ytt_lib/capi-k8s-release/values/_default.yml
config/capi/_ytt_lib/capi-k8s-release/values/images.yml
config/capi/capi.yml
vendir.lock.yml
vendir.yml

Add `uaa.clients.cf_api_controllers.secret_name`
This additive change enables CAPI to update the cf-api-controllers deployment so it uses k8s secrets instead of secrets in the configmap
There are no behavioral changes in this PR. cf-for-k8s should deploy and function as it did before
@cloudfoundry/cf-capi

Add `uaa.clients.cf_api_controllers.secret_name`

---

config/capi/capi.yml

Now that CAPI is using k8s secrets, we no longer need the secret ytt variables
---
cf-for-k8s continues to …

Remove unused capi secrets

---

config/networking/external-routing.yml
config/networking/gateway.lib.yml
config/networking/gateway_test.star
config/values/00-values.yml
sample-cf-install-values.yml

This change adds a setting to the values file that allows users to tell the platform to redirect HTTP requests to the HTTPS endpoint.
Given I have a deployment of cf-k8s with an app,
And I have set `gateway: {https_only: true}`
When I send an http request to that app
Then I can see that I am redirected to https
And I receive a successful response from my application https.
Given I have a deployment of cf-k8s with an app,
And I have set `gateway: {https_only: false}`
When I send an http request to that app
Then I receive a successful response from my application over http.
CC @mike1808 @ndhanushkodi

Add setting to redirect HTTP requests to HTTPS

---

config/minio/minio.yml
config/networking/network-policies.yaml
config/postgres/postgres.yml
config/workloads-namespace.yml
docs/component_authors/networking.md

This PR re-applies the changes from #270 that were temporarily reverted due to issues seen in CI.
* We saw that the external DB validation job [failed](https://release-integration.ci.cf-app.com/teams/main/pipelines/cf-for-k8s/jobs/validate-cf-for-k8s-gke-external-db/builds/37) due to the lack of a `cf-db` namespace
* We saw smoke-tests [failed](https://release-integration.ci.cf-app.com/teams/main/pipelines/cf-for-k8s/jobs/validate-cf-for-k8s-gke/builds/362) due to a timeout after successfully staging

Re-apply "Initial NetworkPolicies for System Components"

---

config/capi/capi.yml

Remove the unused `uaa.clients.cf_api_controllers.secret` value from config/capi/capi.yml
Also bump to a version of capi-k8s-release that no longer uses the value. This will happen automatically tonight, but I wanted to submit the PR sooner.
This PR makes no behavioral changes
@cloudfoundry/cf-capi

Remove unused uaa.clients.cf_api_controllers.secret

---

ci/configure
ci/overlays/inject-pipeline-revision.yaml
ci/overlays/values.yaml
ci/pipelines/cf-for-k8s-contributions.yml

It adds a task to the beginning of every job of every pipeline (created by a template) which prints the current git revision
e.g.:
```yaml
plan:
- task: pipeline-revision-info
config:
platform: linux
image_resource:
source:
repository: busybox
type: docker-image
run:
path: /bin/echo
args:
- -e
- git@github.com:cloudfoundry/cf-for-k8s.git 5c6c847fcdfa25765084d2f659f212c46099cb5f ci/templates/cf-for-k8s-contributions.yml \e[31mdirty\e[0m
```
We do this for quite some time now for our internal pipelines and it is helpful from time to time.  
The current implementation is WIP and has a limitation. If you're interested we can find a way to resolve the limitation:
As the result of the templating process is currently check into git, it will always be marked as dirty (as the result contains the …

[WIP] add revision info task at beginning of every job

---

docs/deploy.md

This is a tiny change to the deploy docs to fix incorrect instances of "it's" where "its" is the correct form.
No
When I look at the deploy docs, there are no incorrect usages of "it's".

Minor docs grammar fix (it's -> its)

---

config/networking/_ytt_lib/cf-k8s-networking/config/crd/networking.cloudfoundry.org_routes.yaml
config/networking/_ytt_lib/cf-k8s-networking/config/istio/generated/xxx-generated-istio.yaml
config/networking/_ytt_lib/cf-k8s-networking/config/routecontroller/cluster-role-binding.yaml
config/networking/_ytt_lib/cf-k8s-networking/config/routecontroller/cluster-role.yaml
config/networking/_ytt_lib/cf-k8s-networking/config/routecontroller/routecontroller-configmap.yaml
config/networking/_ytt_lib/cf-k8s-networking/config/routecontroller/routecontroller.yaml
config/networking/_ytt_lib/cf-k8s-networking/config/routecontroller/service-account.yaml
config/networking/_ytt_lib/cf-k8s-networking/config/values.yaml
vendir.lock.yml
vendir.yml

In our [previous PR](https://github.com/cloudfoundry/cf-for-k8s/pull/349) to bump Istio to version 1.6.4, we accidentally upgraded to only Istio 1.6.0. This PR bumps the cf-k8s-networking component in vendir.yml to a commit that uses Istio 1.6.4 and not Istio 1.6.0.
No
Given I have deployed cf-for-k8s.
When I describe an istio-ingressgateway pod with kubectl -n istio-system get pods -l app=istio-ingressgateway -o yaml | grep image:
Then I can see that the istio-ingressgateway pod uses the image gcr.io/cf-routing/proxyv2:1.6.4
@XanderStrike @ndhanushkodi @keshav-pivotal

bump cf-k8s-networking to include istio 1.6.4 changes

---

config/capi/capi.yml
config/minio/minio.yml
config/values/00-values.yml
config/values/20-secrets-config-values.yml
hack/generate-values.sh

This is one of the first steps towards external blobstores. Documentation, tests, disabling minio when an external blobstore is configured etc. will follow. With this PR, an external blobstore (e.g. S3) can be configured to be used by cf-for-k8s. See #344 for details.
It depends on [capi-release](https://github.com/cloudfoundry/capi-k8s-release/pull/64) to be merged first. 
Yes
1. Create the needed buckets e.g. in S3:
```
aws s3api create-bucket --bucket <cc-buildpacks-bucket> --region eu-central-1 --create-bucket-configuration LocationConstraint=eu-central-1 --acl private
aws s3api create-bucket --bucket <cc-droplets-bucket> --region eu-central-1 --create-bucket-configuration LocationConstraint=eu-central-1 --acl private
aws s3api create-bucket --bucket <cc-packages-bucket> --region …
```

Allow blobstore to be configured

---

ci/pipelines/cf-for-k8s-contributions.yml
ci/pipelines/cf-for-k8s-main.yml
ci/tasks/install-cf-on-gke/task.sh
ci/tasks/run-external-db-validation-test/task.sh
ci/tasks/run-external-db-validation-test/task.yml
ci/templates/cf-for-k8s-contributions.yml

With this change, we verify that the configured database is actually used (#168).
We do so by verifying that tables exist in the public schema for `uaa` and `capi`.
This is implemented for in-cluster databases as well as external (rds) databases.
No
@modulo11 
@phil9909

Add validation test for external database

---

config/networking/network-policies.yaml

The new network policies released in v0.6.0 need some tweaking for eirini to function. Currently, eirini-task-reporter cannot connect to the kube api, and cf-api-server cannot receive calls from eirini-task-reporter.
Also a new eirini component, the instance-index-env-injector service needs a network policy to allow communication to and from the kube api.
No
- Fixes issue #375 so that tasks will show as complete once finished.
- App containers will have the CF_INSTANCE_INDEX env var set appropriately
@cloudfoundry/eirini @mnitchev 
- Our CI …

Fix network policies for eirini

---

config/networking/network-policies.yaml

When an app container crashes, eirini-events will report it to cf-api-server. Create rule to allow this in network policies.
No.
* Run the following:
```
cf push catnip
curl <catnip-url>/sigterm/KILL
cf events catnip
```
* See crash events in the output
@cloudfoundry/eirini

Allow ingress to cf-api-server from eirini-events

---

config/kpack/default-buildpacks.yml

Allow apps to include a Procfile, regardless of the language they are written in. See this [Slack conversation](https://cloudfoundry.slack.com/archives/CH9LF6V1P/p1598642490103900) for details.
No
Push a source app that includes a Procfile. For example, https://github.com/cloudfoundry/cf-acceptance-tests/tree/master/assets/node-with-procfile

Add the Procfile buildpackage to all groups

---

docs/maintaining.md

Just a simple docs update, fixing links that appear to be broken by this file change: docs/contributing.md -> community/CONTRIBUTING.md. Also curious whether this file itself shouldn't be merged with [community/MAINTAINING.md](https://github.com/cloudfoundry/cf-for-k8s/blob/fed095d55e948d9d6a5536fb56ee0b9d13a0c0dd/community/MAINTAINERS.md)?
No
N/A

Fix links in docs/maintaining.md

---

sample-cf-install-values.yml

[#173597144]
Remove metric_proxy from sample values file now that TLS has been removed here: https://github.com/cloudfoundry/cf-for-k8s/pull/391
No

Remove metric_proxy certs from sample values file

---

config/kpack/kpack.yml
config/minio/minio.star
config/minio/minio.yml
config/networking/network-policies.yaml
tests/ytt/blobstore/blobstore-values.yml
tests/ytt/external_blobstore_test.go

With this PR, the installation of minio will be skipped if an external blobstore is configured. See #344 for details.
No
Install with external blobstore, ensure that no `cf-blobstore` namespace is created.
@phil9909 
@loewenstein

Skip minio installation if external blobstore is configured

---

config/kapp-rebase-rules.yml

Refactor the kapp rebase rules to be more concise given the updates kapp has gotten since the previous minimum version. Functionally, the rebase rules should remain unchanged.
No.
Following the deployment docs continues to work normally. After that try redeploying with the same yaml and notice that the deployment succeeds again. (Even if it currently reports a diff in service accounts for which we do not yet have a rebase rule as mentioned in issue #110 .
cc @cloudfoundry/cf-release-integration

Kapp rebase rules

---

config/capi/capi.yml

Resubmitted to appease CI.
this allows us to remove cert configuration and bogus defaults from capi-k8s-release default values files.
This removes a few unnecessary properties from capi.yml that used to configure TLS communication between CAPI and eirini.
No.
It should deploy without a hitch. After this is merged, please poke us to merge cloudfoundry/capi-k8s-release#68 .

remove capi eirini cert config

---

supported_k8s_versions.yml

This was unblocked by 59fa844
Nope
Smoke tests / PR checks pass
- Our CI uses concourse task files from HEAD of the `develop` branch. If your PR includes/requires CI changes, please ping the RelInt interrupt and they'll help apply the CI changes for you.
- Checkout the [contributing …

ENH: bump newest supported K8s version from 1.17 to 1.19

---

sample-cf-install-values.yml

The blobstore key in the sample-cf-install-values.yml file was out of sync with the corresponding data values key in config/values/00-values.yml
No
Use the sample-cf-install-values.yml file to hand-craft a configuration file to deploy with an external blobstore

Update the sample-cf-install-values.yml blobstore key

---

config/uaa/uaa.yml

We are in the process of adding a controller to reconcile routes between the Cloud Controller and Kubernetes APIs and the controller needs to be able to read all routes, spaces, and domains on the platform.
CAPI Story: [#174502491](https://www.pivotaltracker.com/story/show/174502491)
No
For what it's worth, I tested this against a dev branch of capi-k8s-release and verified that our route sync controller could successfully list routes from the CF API once the client had these authorities. If you want to test it more manually you could...
1. Get the client secret value from your values file from `cf_api_controllers_client_secret`. Save this in `$CLIENT_SECRET`
1. Authenticate with the CF CLI using client credentials: `cf auth cf_api_controllers $CLIENT_SECRET --client-credentials`
1. `cf …

add additional authorities to cf_api_controllers UAA client

---

docs/deploy.md

- Remove unnecessary distractions
- Reduce the number of options and instead choose the easiest option (e.g. dockerhub over gcr/acr)
- Add roadmap/milestones at the end
Running through the steps should install a successful cf-for-k8s

Make the docs simpler

---

ci/tasks/run-external-blobstore-validation-test/task.sh
config/capi/_ytt_lib/capi-k8s-release/templates/api_server_deployment.yml
config/capi/_ytt_lib/capi-k8s-release/templates/cc-kpack-registry-service-account.yml
config/capi/_ytt_lib/capi-k8s-release/templates/ccng-config.lib.yml
config/capi/_ytt_lib/capi-k8s-release/templates/nginx-configmap.yml
config/capi/_ytt_lib/capi-k8s-release/templates/service.yml
config/capi/_ytt_lib/capi-k8s-release/values/images.yml
config/eirini/eirini.yml
config/networking/istio-authorization-policies.yml
config/networking/network-policies.yaml
vendir.lock.yml
vendir.yml

This change does the following:
* Configures Cloud Controller to use the same OCI image registry that kpack uploads droplets to for package uploads (https://github.com/cloudfoundry/cf-for-k8s/issues/409)
* Moves the `/internal` CF API endpoints to a separate port
* Adds additional `NetworkPolicy` and Istio `AuthorizationPolicy` resources to further protect these internal endpoints
* Temporarily updated `vendir.yml` to point to a branch of capi-k8s-release.
After this is merged, we will merge the capi-k8s-release branch (`secure-cf-api-internal-endpoints-174455375`) and y'all can re-enable the auto-bumping of capi-k8s-release in your CI.
Nope
Run smoke tests. `cf push` should still work. 🙂
@jspawar @cloudfoundry/cf-capi 
- https://github.com/cloudfoundry/cf-for-k8s/issues/409
- …

Use Image Registry for Package Uploads and Secure Internal CF API Endpoints

---

config/istio/remove-hpas-and-scale-istiod.yml

Co-authored-by: Kauana dos Santos <kdossantos@vmware.com>
Co-authored-by: Alex Standke <astandke@vmware.com>
Co-authored-by: Clay Kauzlaric <ckauzlaric@vmware.com>
Co-authored-by: Nitya Dhanushkodi <ndhanushkodi@pivotal.io>
- the ingressgateway one does not function, because we deploy a
daemonset
- we know from previous research that hpas do not help overloaded
pilot/istiods
- defaults to 1 istiod for proof-of-concept/local deployments
[#174764287](https://www.pivotaltracker.com/story/show/174764287)
No
When I deploy cf-for-k8s with this PR
I can see that istiod has 1 replica with `kubectl get pods -n istio-system`
@kauana @KauzClay @XanderStrike

remove HPA and fix istiod replicas to 1

---

ci/tasks/install-cf-on-kind/only-nodejs-builder-overlay.yml
config/capi/_ytt_lib/capi-k8s-release/templates/api_server_deployment.yml
config/capi/_ytt_lib/capi-k8s-release/templates/cc-kpack-registry-service-account.yml
config/capi/_ytt_lib/capi-k8s-release/templates/ccdb-migrate-job.yaml
config/capi/_ytt_lib/capi-k8s-release/templates/ccng-config.lib.yml
config/capi/_ytt_lib/capi-k8s-release/templates/cf-api-controllers-service-account.yml
config/capi/_ytt_lib/capi-k8s-release/templates/cf-api-server-service-account.yml
config/capi/_ytt_lib/capi-k8s-release/templates/cf-api-worker-service-account.yml
config/capi/_ytt_lib/capi-k8s-release/templates/clock_deployment.yml
config/capi/_ytt_lib/capi-k8s-release/templates/controllers_deployment.yml
config/capi/_ytt_lib/capi-k8s-release/templates/deployment_updater_deployment.yml
config/capi/_ytt_lib/capi-k8s-release/templates/nginx-configmap.yml
config/capi/_ytt_lib/capi-k8s-release/templates/periodic-route-sync.yml
config/capi/_ytt_lib/capi-k8s-release/templates/periodic-sync-crd.yml
config/capi/_ytt_lib/capi-k8s-release/templates/worker_deployment.yml
config/capi/_ytt_lib/capi-k8s-release/values/_default.yml
config/capi/_ytt_lib/capi-k8s-release/values/images.yml
config/kpack/_ytt_lib/kpack/release-0.1.2.yaml
config/kpack/default-buildpacks.yml
config/kpack/kapp-order.yml
config/kpack/kapp-wait-rules.yml
config/kpack/kpack.yml
vendir.lock.yml
vendir.yml

This bumps kpack to its latest stable version (0.1.2); however, this introduced breaking changes which required multiple changes to `capi-k8s-release` and its underlying source code (`cloud_controller_ng` + `cf-api-controllers`)
As a result, in order to minimize the amount of pipelines breaking on both our and RelInt's ends, we created a branch which introduces the changes needed to our k8s templates plus bumping to images we hand-crafted (instead of through automation) which contain the changes needed in our source to accommodate kpack's breaking changes. 
We have confirmed basic functionality continues to work (i.e. `cf push catnip`)
Maybe also worth mentioning this was forked off a branch you all made to bump kpack (`kpack-bump-0.1.1`); this required some additional changes beyond the …

Bump to latest stable kpack (0.1.2) and latest capi-k8s-release which supports that kpack

---

config/networking/istio-authorization-policies.yml
config/networking/network-policies.yaml

When we moved the internal CF API endpoints to a different port (this was merged in https://github.com/cloudfoundry/cf-for-k8s/pull/430) we failed to account for the staging completion callback endpoint that Eirini uses when "staging" docker apps. This was reported in https://github.com/cloudfoundry/cf-for-k8s/issues/465.
We're working on getting the following code fixes through our pipeline:
* https://github.com/cloudfoundry/cloud_controller_ng/commit/1ea8e8b6b37acfd6133696f74f6bf0410c3e124c
* https://github.com/cloudfoundry/capi-k8s-release/commit/0022eec851a10213138bfd4a2497ec2eeadabecd
Once those are through, `cf-for-k8s` should consume the latest `ci-passed` of `capi-k8s-release`.
This PR, though, is a necessary step for allowing Eirini to talk to that endpoint.
CAPI Story …

Allow Eirini to hit internal CF API endpoints

---

docs/deploy.md

Teeny tiny one character fix to a markdown mistake in the deploy docs.
No
When I read the deploy docs on GitHub, the link to the milestones is clickable.

Tiny: fix markdown mistake in docs

---

docs/deploy.md

Co-authored-by: Clay Kauzlaric <ckauzlaric@vmware.com>
To document that clusters should require Network Policy support
No
When I read the docs to deploy cf-for-k8s,
I can understand that my cluster needs to have a CNI that supports network policy.
@KauzClay @keshav-pivotal @shalako

doc: cluster requires network policy support

---

config/networking/network-policies.yaml

* We decided that renaming this network policy to
"only-allow-istio-control-plane" because it better describes what this
policy does. It is a policy that allows traffic from the istio to all
pods in a namespace.
[174810340](https://www.pivotaltracker.com/story/show/174810340)
Co-authored-by: Rodolfo Sanchez <srodolfo@vmware.com>
>
> Rename a network-policy to better describe the scope of it
> no 
```
When I have a cluster with cf-for-k8s 
And I get the network policies in all namespaces `kubectl get netpol -A  | grep allow-istio-control-plane`
Then I can see network policies called only-allow-istio-control-plane.
And I do not see network policies called …
```

Rename allow-istio-control-plane network policy

---

config/capi/capi.yml
config/values/00-values.yml

Allow the operator to change the log level of the Cloud Controller components (i.e. cf-api-server, cf-api-worker, cf-api-clock)
Yes
This command lists all of the log levels present in CC containers:
```
kapp -a cf logs --pod-name 'cf-api-%' | grep log_level | cut -d '|' -f 2- | jq -r .log_level | sort -u
```
Before deploying this change, this should only list `info`.
To verify this change, add the `capi.log_level` property to your `values.yml` with a value of `"debug"`. After deploying with that values file, the above `kapp` command should list both `info` and `debug`.
@piyalibanerjee @pivotal-mikegresham 
Relevant tracker story: https://www.pivotaltracker.com/story/show/172847921

Make cc log level configurable

---

build/istio/istioctl-values.yaml
build/istio/values.yaml
config/istio/istio-generated/xxx-generated-istio.yaml
config/istio/upgrade-istio-sidecars-job.yml

Co-authored-by: Clay Kauzlaric <ckauzlaric@vmware.com>
Co-authored-by: Kauana Dos Santos <kdossantos@vmware.com>
Bumping to new version of istio. We had to make a small change in the istio-values. The accessLogEncodings parameter is on the meshConfig struct now, not the Proxyconfig.
[#174638038](https://www.pivotaltracker.com/story/show/174638038)
No
```gherkin
Given a deployed cf-for-k8s enviroment
When I inspect pods in the istio-system namespace 
Then I see the label cloudfoundry.org/istio_version: 1.7.0
```
To examine a pod in the `istio-system` namespace, use:
`kubectl get pods -n istio-system <pod-name> -oyaml | grep istio_version`
@kauana @ndhanushkodi @keshav-pivotal

Bump Istio to 1.7.1

---

config/eirini/eirini.yml
config/istio/external-routing.yml
config/logging/logging.yml
config/minio/minio.yml
config/postgres/postgres.yml
config/uaa/uaa.yml
config/values/00-values.yml
config/values/20-secrets-config-values.yml
docs/platform_operators/deploy-parameters.md
docs/platform_operators/setup-ingress-certs-with-letsencrypt.md
hack/generate-values.sh
sample-cf-install-values.yml
tests/ytt/uaa/uaa-values.yml
tests/ytt/uaa_test.go

This change allows operators to provide PEM-encoded system and workloads certificates that are not base64 encoded. It moves the bas64 encoding logic into the templates where the values are provided to components. It also cleans up some cruft in the generated values.yml file. This PR addresses issue #460.
Yes
Generate a config values file with system and workloads certificates that are NOT base64 encoded, deploy and run smoke-tests.

ENH: Allow operators to provide PEM-encoded certs

---

docs/platform_operators/networking-metrics.md

[#174239599](https://www.pivotaltracker.com/story/show/174239599)
Adds a doc describing metrics of interest to operators who would like to observe their platform's networking performance
No
```
AS an operator
WHEN I view these docs
THEN I am enlightened
```
@ndhanushkodi @cloudfoundry/cf-for-k8s-networking

add networking metrics docs

---

build/istio/istioctl-values.yaml
config/istio/external-routing.yml

- Deployments should be an option too if user wants to scale their cluster up and having an istio-ingressgateway per node is too much.
[#171678788](https://www.pivotaltracker.com/story/show/171678788)
Co-authored-by: Leah Hanson <lhanson@pivotal.io>
> No. 
**When** I configure the istio-ingressgateway to be a Deployment
**Then** I expect the deployment to be successful
@astrieanna

Expect ingressgateway to be either a Deployment or DaemonSet

---

hack/generate-values.sh

We are moving into a world where HTTP clients and servers expect all certificates to include their common name in the list of subject alternative names. We should get ahead of this by ensuring that all certificates we generate conform to this pattern.
No
Deploy, push an app, and attempt to communicate with that app over TLS with a client that enforces the requirement that the server certificate includes their common name in the list of subject alternative names.
@paulcwarren @julian-hj

ENH: Add SAN definitions to generated certs

---

docs/deploy.md

Adding required pod capabilities for Istio, with a link to explain why.
No
When I read the deploy docs, I understand that the cluster requirements are that any PodSecurityPolicies must allow pods to have `NET_ADMIN` and `NET_RAW` capabilities. 
@mike1808 @keshav-pivotal @shalako 
[#175079859](https://www.pivotaltracker.com/story/show/175079859)
Co-authored-by: Mikael Manukyan <mmanukyan@vmware.com>

doc: required pod capabilities for Istio

---

config/capi/_ytt_lib/capi-k8s-release/templates/ccng-config.lib.yml
config/capi/_ytt_lib/capi-k8s-release/templates/secrets.lib.yml
config/capi/_ytt_lib/capi-k8s-release/values/_default.yml
config/capi/capi.yml
vendir.lock.yml
vendir.yml

Use the capi-database-encryption-key-secret in capi to encrypt the database. Formerly we used "TODO"
NOTE: this commit manually bumps to a newer version of capi-k8s-release. Without this manual bump, this PR would cause cf-for-k8s to fail to deploy (due to ytt overlay issues)
NO
cf-for-k8s should continue to deploy successfully. There's no external test for the db encryption key. This is a chore on the CAPI/KAT/CAKE side.
@njbennett 
Here's our story for this work: https://www.pivotaltracker.com/story/show/175080272

Use the capi-database-encryption-key-secret in capi-k8s-release

---

build/istio/istioctl-values.yaml

>
Enable Prometheus stats merge for sidecar and app metrics
* this feature is enabled by default thus no config changes
* we are committing this to ensure this behavior for future Istio versions
No
Works as before

Merge Istio sidecar and app stats

---

build/istio/istioctl-values.yaml
config/istio/istio-generated/xxx-generated-istio.yaml

This change will cause application containers to not start until the `istio-proxy` container is not up. This will prevent issues when the application requires network connectivity right at the start.
One caveat about how this works:
>Something to note here is that this feature leverages an undocumented behaviour of the Kube runtime. The fact that the kubelet blocks the startup of subsequent containers is largely an unintended feature and happenstance.
>
>There have been efforts to change this core behaviour of Kubernetes:
>
>kubernetes/kubernetes#81450
>https://github.com/kubernetes/kubernetes/pull/82282/files
>kubernetes/kubernetes#86115
>
>So we must be aware that there is a possibility of this unintended feature being removed even before SIdecar container first-class support is added: …

Make application wait for sidecar proxy before starting

---

build/istio/istioctl-values.yaml
config/istio/istio-generated/xxx-generated-istio.yaml

[#175148731](https://www.pivotaltracker.com/story/show/175148731)
Co-authored-by: Mikael Manukyan <mmanukyan@vmware.com>
Removes the merging of sidecar and workload stats, the metrics team will scrape each container independently.
- this caused some problems for the metrics team
- namely, it causes metrics to be emitted in plaintext
Nope
N/A
@mike1808 @cloudfoundry/cf-for-k8s-networking

Disable prometheus metrics merging

---

build/eirini/osl-compliant-image-override.yml
ci/pipelines/build-eirini-images.yml
ci/templates/build-eirini-images.yml
config/eirini/_ytt_lib/eirini/rendered.yml

This PR configures cf-for-k8s to use a forked and patched version of Eirini images that loosens the UID requirement. It removes the UID 2000 requirement, while still requiring non-root through the security context
No.
Deploy with a stack that has a non-2000 (non-root) UID. The reference set we used is contained in this PR: https://github.com/cloudfoundry/cf-for-k8s/pull/487
@paulcwarren @acosta11

Fork and patch Eirini to loosen UID requirement

---

build/istio/istioctl-values.yaml
config/istio/istio-generated/xxx-generated-istio.yaml

This reverts commit d0fafb31bdfe70a17b1928c9d21c6469a341a30b, reversing changes made to ade4b94637c2ecc922d988e484b357230a03b5a6.
We're enabling this back, because we cannot make Prometheus scrape metrics over mTLS because of https://github.com/istio/istio/issues/27824 
No
Tests should pass

Revert "Merge pull request #512 from cloudfoundry/disablePrometheusMerge"

---

build/istio/values.yaml
config/istio/istio-generated/xxx-generated-istio.yaml
config/istio/upgrade-istio-sidecars-job.yml

Bump Istio bugfix version to 1.7.3
No
```
Given a deployed cf-for-k8s enviroment
When I inspect pods in the istio-system namespace 
Then I see the label cloudfoundry.org/istio_version: 1.7.3
```

Bump Istio to 1.7.3

---

build/istio/build.sh
config/istio/upgrade-istio-sidecars-job.yml

Co-authored-by: Kauana dos Santos <kdossantos@vmware.com>
We want to avoid having `.`s in pod names because some platforms don't
allow that.
[#175169873](https://www.pivotaltracker.com/story/show/175169873)
No
**When** I have a cluster with cf-for-k8s deployed
**And** I describe the `restart-sidecar-job` with `k get po -n cf-workloads | grep "restart"`
**Then** I see that the pod name is `restart-workloads-for-istio1-7-1-<hash>` and **not** `restart-workloads-for-istio1.7.1-<hash>`
@kauana @cloudfoundry/cf-for-k8s-networking

reformat version in upgrade job

---

build/istio/overlays/ingressgateway-as-root.yaml
config/istio/istio-generated/xxx-generated-istio.yaml

We need to run Ingressgateway as root to allow fluent-bit sidecar to access Docker container logs as only root user can view them. 
It's required for `cf logs` command to show access logs of the app.
[#175210582](https://www.pivotaltracker.com/story/show/175210582)
Closes #520 
No
`cf logs <app_name>` shows the access logs of the app

Run Istio Ingressgateway pod as root

---

docs/platform_operators/setup-ingress-certs-with-letsencrypt.md

Update the Let's Encrypt doc with corrected examples now that ingress certificates do not need to be base64 encoded.
No
Validate that the docs are up to date.

DOC: Update setup-ingress-certs-with-letsencrypt

---

docs/platform_operators/scaling.md

Adds documentation for platform operators about how to scale cf-for-k8s.
This uses some networking scaling documentation that was introduced by @KauzClay and @XanderStrike in #473 
Nope
tagging @acosta11 
original story link: https://www.pivotaltracker.com/story/show/174900829

Add Scaling documentation

---

config/capi/_ytt_lib/capi-k8s-release/values/images.yml
vendir.lock.yml
vendir.yml

- This pulls in a new cloudfoundry/cloud-controller-ng image that
includes a bug fix that resolves the UnknownErrors users would get when
deleting docker apps
- It fixes https://github.com/cloudfoundry/capi-k8s-release/issues/84
No
1. `cf enable-feature-flag diego_docker`
1. `cf push my-docker-app -o cfrouting/proxy`
1. `cf delete my-docker-app`
All of these commands should succeed. Previously these would fail with errors like:
```console
cf delete mando
Really delete the app mando? [yN]: y
Deleting app mando in org o / space s as admin...
Job (fc182fce-18a2-4db2-aecb-15e7f59cd3a1) failed: An unknown error occurred.
FAILED
```
You can see https://github.com/cloudfoundry/capi-k8s-release/issues/84  and [#175295965](https://www.pivotaltracker.com/story/show/175295965) for more information. …

Bump capi-k8s-release to 29b77b94183a26cefdc98eff5825f22ae6c75090

---

tests/smoke/smoke_test.go

- docker apps are a requirement
- the lack of any testing in relint's pipelines has caused several regressions that block teams

ci: add docker app test to smoke tests

---

ci/pipelines/cf-for-k8s-stability-tests.yml
docs/platform_operators/rotating-secrets-and-certs.md

Document which fields currently are not correctly rotated, and point to bugs.
Additionally, point out which fields are rotated, but cause a CI job to fail when they're changed due to the way the job is written.
No
Mostly, verify that the updater jobs in CI, like `cf-for-k8s-stability-tests/validate-values-rotation-redeploy` passes. 
Note that this is mostly a documentation change. It can be verified by changing one of the fields listed in [the rotation doc](https://github.com/cloudfoundry/cf-for-k8s/blob/175210100-update-secret-rotation-branch/docs/platform_operators/rotating-secrets-and-certs.md#specific-issues), redeploy, and verify the foundation still works.
@jamespollard8 
[x] - Make sure this PR is based off the `develop` branch
[x] - Include any links to related PRs, issues, …

175210100 update secret rotation branch

---

docs/deploy.md
docs/platform_operators/external-blobstore.md
docs/platform_operators/external-databases.md

Clarify that the internal database and blobstore and intended for the kick-the-tyres user only. 
All other users should configure their deployment with external database and blobstore.
[#175406567](https://www.pivotaltracker.com/story/show/175406567)

DOCS: add statement to clarify internal database and blobstore usage

---

config/capi/capi.yml
config/get_missing_parameters.star
config/uaa/uaa.yml
config/values/20-secrets-config-values.yml
docs/platform_operators/config-values.md
hack/generate-values.sh
sample-cf-install-values.yml
tests/ytt/missing_attributes_test.go
tests/ytt/uaa/uaa-values.yml

This adds a UAA client will be used by the cf-api-backup-metadata-container to scrape some metadata about the CF installation to include as part of a Velero backup.
See this doc for more information:
https://docs.google.com/document/d/1aR6_v0wTrSWpH9G2XqHcUTsdCNzP82ZsiWUxiN-4Zno/edit#heading=h.9fh5dt50qkx0
CAKE Story: [#175469923](https://www.pivotaltracker.com/story/show/175469923)
Yes
You can test that this client was successfully created by:
1. Authenticating with UAA / CF API
```
cf auth cf_api_backup_metadata_generator <generated-client-secret> --client-credentials
```
2. Curl some endpoints and see them succeed
```
cf curl /v3/spaces
```
cc/ @cloudfoundry/cf-api-kubernetes-evolution @neil-hickey

add cf_api_backup_metadata_generator UAA client

---

docs/deploy.md

- looks like using roman numerals breaks indented codefences (?)
- using Arabic numerals _does_ work (and delightfully, renders as roman numerals at the 2nd-level)

(minor) fix codefence in deploy instructions

---

docs/platform_operators/networking/networking-metrics-and-monitoring.md

This is exploration PR. Please don't merge it.
Update the operator's networking metrics guide with Contour metrics.
No

Explore Contour metrics

---

config/capi/capi.yml

This is a followup PR for a mistake made in https://github.com/cloudfoundry/cf-for-k8s/pull/555.
It includes a pending change to the cf-api-controllers deployment so that this is adequately tested by CI
It is OK if that change is reverted since it will come through via a vendir sync in the future and works fine without it for now.
That can either be done through CI naturally as it bumps to the latest capi-k8s-release or manually while merging this.
No
Same as https://github.com/cloudfoundry/cf-for-k8s/pull/555. You should be able to do something like this and see it work after the deploy has succeeded:
```
kubectl exec -n cf-system cf-api-controllers-6cb4d79d5c-z6ntn -c backup-metadata-generator -- "/cnb/process/generate-metadata"
```
CAKE Story: …

fix secret_name for cf_api_backup_metadata_generator client

---

ci/tasks/run-cats/task.sh
ci/tasks/run-cats/task.yml

- Add the option to provide DNS_DOMAIN and CF_ADMIN_PASSWORD as Concourse
params.
> No
> Run cats ci task and it continues to work.
> @jamespollard8

Improve run-cats ci task.

---

docs/platform_operators/rotating-secrets-and-certs.md

[#175313436](https://www.pivotaltracker.com/story/show/175313436)
Co-authored-by: Andrew Wittrock <awittrock@vmware.com>
Continuation of PR #538 
Doc change only to `docs/platform_operators/rotating-secrets-and-certs.md`
> Read the change
> Agree with them and accept the change or disagree and get back to us
Eric and @Birdrock 
Original story at https://www.pivotaltracker.com/story/show/175210100

Note that `uaa.database.password` is currently not rotatable

---

build/eirini/osl-compliant-image-override.yml
ci/pipelines/build-eirini-images.yml
ci/templates/build-eirini-images.yml
config/eirini/_ytt_lib/eirini/rendered.yml

- Avoids rate limiting in dockerhub through cloudfoundry organization open source exemption
- Rebuilt using build-eirini-images pipeline
nope
PR tests pass
@Birdrock 
Original story: https://www.pivotaltracker.com/story/show/175102386

Move Eirini images to cloudfoundry dockerhub

---

build/eirini/osl-compliant-image-override.yml
config/eirini/_ytt_lib/eirini/rendered.yml

- previously, these overrides were configured to map base eirini 1.9 images to our temporarily forked eirini images
[#175238690](https://www.pivotaltracker.com/story/show/175238690)
No
PR tests pass (importantly CATS)
- Our CI uses concourse task files from HEAD of the `develop` branch. If your PR includes/requires CI changes, please ping the RelInt interrupt and they'll help apply the CI changes for you.

ENH: update to using eirini 2.0 images

---

config/istio/remove-resource-requirements.yml

If the config variable `remove_resource_requirements` is set to true, the resource requirements should also be removed from the istio init containers and also from `StatefulSets` and `Jobs`.
See also [post in Slack](https://cloudfoundry.slack.com/archives/CH9LF6V1P/p1605189845132000)
No
* Install cf-for-k8s with `remove_resource_requirements=true`
* The resource requirements of all installed pods should be missing or should be zero
@loewenstein, @Haegi , @phil9909

Remove resource requirements also from istio init container

---

tests/smoke/smoke_test.go

>
This passes through environment variables to the smoke tests for dockerhub authentication. Related to https://github.com/cloudfoundry/cf-for-k8s/issues/580.
No
- Is there anything else of note that the …

Allow docker auth for smoke tests

---

build/eirini/osl-compliant-image-override.yml
config/eirini/_ytt_lib/eirini/rendered.yml

This PR achieves what #578 was supposed to.
- the eirini images this replaces were accidentally still based off our
fork of eirini from before v2.0.0
This also depends on commit e193bcc , which moved the pipeline off of our temporary eirini 1.9.0+ branch (done while we were waiting for eirini 2.0.0 to ship).
[#175238690](https://www.pivotaltracker.com/story/show/175238690)
Co-authored-by: James Pollard <pollardja@vmware.com>
- sufficient for smoke tests and CATs to pass, given how this changes the images for running apps.

FIX: Update the eirini image SHAs

---

supported_k8s_versions.yml

Simply bumping this value should trigger testing it in CI via the `newest-kind` job.

Bump supported k8s versions to include v1.20.0

---

tests/smoke/assets/test-node-app/server.js
tests/smoke/smoke_test.go

- Make logging happen more frequent to mitigate lossiness
[#175542566](https://www.pivotaltracker.com/story/show/175542566)
Signed-off by: Tim Downey tdowney@vmware.com
The smoke test for logging was unrealistic because it only emitted a single log. We made the smoke test app emit 1 log/second to overcome potential lossiness. 
No
The smoke tests should be less flaky
@tcdowney @angelachin

Re add logging to smoke test

---

build/minio/build.sh
build/minio/osl-compliant-image-override.yml
config/minio/_ytt_lib/minio/rendered.yml

- the image came from minio/minio:RELEASE.2020-06-14T18-32-17Z and has
been annotated and moved into the not-rate-limited cloudfoundry
dockerhub
Nope
Smoke tests (PR tests) pass
and
The minio image used in cf-for-k8s rendered templates comes from cloudfoundry docker hub and has deplab annotations on it when you `docker inspect` the image

ENH: use an annotated minio image

---

deploy/kind-on-gcp/terraform/vm.tf

- kind v0.8.0 -> v0.9.0
- ginkgo v1.11.0 -> v1.14.2
- add retry to carvel tools download
[#174887425](https://www.pivotaltracker.com/story/show/174887425)
Nope
PR tests pass, specifically the KinD ones

CI-MAINT: bump dependencies of KinD tests

---

config/networking/network-policies.yaml

Eirini has split the instance-index-env-injector component into a webhook registration job and a webhook service deployment to facilitate scaling and to remove cluster permissions from the webhook service.
The webhook service requires network to and from the control plane as before, so the eirini-instance-index-env-injector 
network policy is being left as is. The new registration job requires outbound network access to the control plane so we are adding this new network policy targeting the job.
This change is required to support versions of eirini > v2.0.0.
Story: https://www.pivotaltracker.com/story/show/175878489
No
- Deploy cf-for-k8s with the latest eirini-release from master. See that the cf-system/instance-index-env-injector job completes successfully (if not kapp deployment will …

Add network policy for eirini webhook registration job

---

deploy/kind/cluster.yml

- Kind should now be using a new enough version of containerd (v1.4.2+) such that this work-around isn't required
- Related to #444
PR tests pass, specifically the KinD tests

MAINT: remove KinD patch to disable snapshot annos

---

build/eirini/osl-compliant-image-override.yml
config/eirini/_ytt_lib/eirini/rendered.yml

- Rebuilt to Eirini commit 3dcf72f to align with v2.0.0 release standard
images
Signed-off-by: Andrew Costa <ancosta@vmware.com>
>
There was drift in the OSL image base refs during the v2.1.0 release when Eirini was updated.
No.
Check revision info in deplab labels on image inspect.
```
docker inspect <image> | jq .
```

Rebuilt Eirini images to 2.0.0 release

---

config/capi/capi.yml
config/values/00-values.yml
tests/ytt/capi/capi-values.yml
tests/ytt/capi_test.go

This PR removes the update strategy from the CF API pods as it can cause API downtime during upgrades. See [#177444748](https://www.pivotaltracker.com/story/show/177444748) for details.
No
Deploy v2.1.1, then deploy this change while monitoring the `cf-api-server` pod. You should see that the old pod is not terminated until the new pod is ready.

Remove cf api server update strategy

---

images/build/capi/generate-kbld-config.sh
images/build/capi/kbld.yml

[finishes #177481547](https://www.pivotaltracker.com/story/show/177481547)
Signed-off-by: Andrew Costa <ancosta@vmware.com>
Co-authored-by: Andrew Costa <ancosta@vmware.com>
>
Add OCI labels to nginx images built with Carvel toolchain.
No.
Docker inspect a produced image (pipe to `jq .[].Config.Labels`) and search for opencontainers annotations.
- Our CI uses concourse task files from HEAD of the `develop` …

Added OCI labels to capi nginx kbld config

---

build/istio/istioctl-values.yaml
build/istio/values.yaml
ci/pipelines/cf-k8s-networking-istio-upgrade.yml
config/istio/istio-generated/xxx-generated-istio.yaml
config/istio/istio-kapp-ordering.yml
config/istio/upgrade-istio-sidecars-job.yml

- support for Istio v1.7 is ending today, Feb 19
Closes #622
Nope
PR tests pass, and I see that Istio has been upgraded to v1.8.0+
👀 @braunsonm
- Our CI uses concourse task files from HEAD of the `develop` branch. If your PR includes/requires CI changes, please ping the RelInt interrupt and they'll help apply the CI changes for you.

ENH: bump Istio from v1.7.3 to v1.8.0

---

config/minio/inject-images.yml
config/values/10-minio-images.yml
tests/ytt/external_blobstore_test.go

[#177585539](https://www.pivotaltracker.com/story/show/177585539)
Co-authored-by: Andrew Costa <ancosta@vmware.com>
Make the images used by the minio templates configurable via data value driven ytt overlays.
Yes. Adds values block for minio image.
Deploy as normal and ensure still working.
@acosta11
[#177585539](https://www.pivotaltracker.com/story/show/177585539)

ENH: Make minio images configurable

---

config/istio/inject-images.yml
config/values/10-images.yml
config/values/10-istio-images.yml

Make the images used by the istio templates configurable via data value driven ytt overlays.
Yes, adds a new data values block for istio images.
Rendering and deploying cf-for-k8s continues to work normally by default.
Update the `10-istio-images.yml` data values and notice that rendering cf-for-k8s now updates the images used in the istio-ingressgateway daemonset, istiod deployment, and the sidecar pods injected to workloads.
@Birdrock 
[#177585539](https://www.pivotaltracker.com/story/show/177585539)

ENH: Make istio images configurable

---

config/postgres/inject-images.yml
config/values/10-postgres-images.yml
tests/ytt/external_db_test.go

[#177585539](https://www.pivotaltracker.com/story/show/177585539)
Co-authored-by: Andrew Costa <ancosta@vmware.com>
Make the images used by the postgres templates configurable via data value driven ytt overlays.
Yes. Adds values block for minio image.
@acosta11
[#177585539](https://www.pivotaltracker.com/story/show/177585539)

ENH: Make postgres images configurable

---

build/istio/build.sh
config/istio/add-istio-version-to-podspecs.yml
config/istio/istio-version.star
config/istio/upgrade-istio-sidecars-job.yml

This PR adds an Istio version label to all system components. This will cause kapp to roll the components whenever the Istio version changes, which will result in the new version of the proxy sidecar being injected into the pods.
[#177914742](https://www.pivotaltracker.com/story/show/177914742)
No
Deploy a previous version of cf-for-k8s that includes an old version of Istio, then upgrade to this version and confirm that all system component pods are rolled during the upgrade, and that kapp waits for them all to be ready again before proceeding.
@Birdrock

ENH: Add an Istio version label to all system components

---

build/istio/istioctl-values.yaml
config/istio/istio-generated/xxx-generated-istio.yaml

When we run the `build/istio/build.sh` script with istioctl 1.9.4, we saw a deprecation warning about the `holdApplicationUntilProxyStarts` configuration:
```
$ ./build/istio/build.sh
generating Istio resource definitions...
! values.global.proxy.holdApplicationUntilProxyStarts is deprecated; use meshConfig.defaultConfig.holdApplicationUntilProxyStarts instead
resolve | final: cloudfoundry/cf-k8s-networking-fluentbit@sha256:2b8563a032c007bdb5f8a1cdbd093edd8505fadd21a3443a2b891e87caee7504 -> index.docker.io/cloudfoundry/cf-k8s-networking-fluentbit@sha256:2b8563a032c007bdb5f8a1cdbd093edd8505fadd21a3443a2b891e87caee7504
resolve | final: index.docker.io/istio/pilot:1.9.4 -> index.docker.io/istio/pilot@sha256:a613e4535cad4028d0aca7e16450f16f41ed2466fa522f6c22c2b96bfbc26eba
resolve | final: …
```

Update the holdApplicationUntilProxyStarts Istio setting

---

build/istio/overlays/kapp-compatible.yaml
build/istio/values.yaml
config/istio/istio-generated/xxx-generated-istio.yaml
config/istio/istio-version.star
config/z-kapp-versioned-creds.yml
supported_k8s_versions.yml

- Upgrade Istio version for further support window.
- Increases Kubernetes cluster version support range to 1.18 - 1.21.
Co-authored-by: Dave Walter <walterda@vmware.com>
Bumps Istio from 1.9.5 to 1.10.2
No.
Deploy as normal and run smoke tests.

Bump Istio to 1.10.2.

---

config/z-kapp-versioned-creds.yml

- Istio changed how ConfigMaps are read: [istio/istio#31410](https://github.com/istio/istio/pull/31410)
- Stop versioning Istio ConfigMap since Istio will periodically re-read it directly.
Co-authored-by: Andrew Wittrock <awittrock@vmware.com>
Istio changed how ConfigMaps are read. cf-for-k8s is Kapp versioning the `istio` `ConfigMap`, causing Istio to not detect it.
No.
* Standard tests.
* Change `istio` `ConfigMap` to different configuration and observe propogation.

Stop kapp versioning istio ConfigMap.

---

config/networking/network-policies.yaml

Add a network policy egress rule to allow IaaS metadata lookup. Lookup times have been causing 2+ minute startup times for `istio-proxy`.
No.
Deploy and run tests as normal.
@davewalter

Add network policy egress rule for IaaS metadata
